-- Only the never-used H3 schema can be reverted. Evidence must survive rollback.
CREATE TEMP TABLE h3_rollback_guard(value INTEGER CHECK(value=0));
INSERT INTO h3_rollback_guard SELECT count(*) FROM libraries;
DROP TABLE h3_rollback_guard;
DELETE FROM role_permissions WHERE role_id IN ('library_reader','library_manager','library_auditor');
DELETE FROM roles WHERE id IN ('library_reader','library_manager','library_auditor');
DROP TABLE root_plans;
DROP TABLE idempotency_requests;
DROP TABLE document_history;
DROP TABLE notification_receipts;
DROP TABLE document_notifications;
DROP TABLE search_audit_details;
DROP TABLE scan_file_observations;
DROP TABLE root_scans;
DROP TABLE job_attempts;
DROP TABLE jobs;
DROP TABLE pages_fts;
DROP TABLE indexed_pages;
DROP TABLE documents;
DROP TABLE extraction_pages;
DROP TABLE physical_file_locations;
DROP TABLE extraction_runs;
DROP TABLE content_versions;
DROP TABLE physical_files;
DROP TABLE logical_folder_views;
DROP TABLE root_operations;
DROP TABLE storage_root_configuration_versions;
DROP TABLE storage_roots;
DROP TABLE library_role_assignments;
DROP TABLE libraries;
DELETE FROM schema_migrations WHERE name='0002_linked_libraries.up.sql';
