-- Reversal is only supported for an unused installation; no historical evidence is erased.
CREATE TEMP TABLE h4_rollback_guard(value INTEGER CHECK(value=0));
INSERT INTO h4_rollback_guard SELECT count(*) FROM libraries;
DROP TABLE h4_rollback_guard;
DROP TRIGGER documents_classification_insert;
DROP TRIGGER documents_classification_update;
DROP INDEX documents_case_status;
DROP INDEX documents_library_filters;
DROP TABLE upload_items;
DROP TABLE upload_batches;
ALTER TABLE documents DROP COLUMN case_id;
ALTER TABLE documents DROP COLUMN category_id;
ALTER TABLE documents DROP COLUMN document_type_id;
ALTER TABLE documents DROP COLUMN created_by;
ALTER TABLE documents DROP COLUMN metadata_json;
DROP TABLE case_requirements;
DROP TABLE cases;
DROP TABLE template_requirements;
DROP TABLE template_versions;
DROP TABLE templates;
DROP TABLE document_types;
DROP TABLE categories;
DROP TABLE library_configuration_versions;
ALTER TABLE libraries DROP COLUMN settings_json;
ALTER TABLE root_plans DROP COLUMN storage_source;
DELETE FROM role_permissions WHERE role_id IN ('library_contributor','library_reviewer');
DELETE FROM roles WHERE id IN ('library_contributor','library_reviewer');
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='documents.upload';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='documents.classify';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='documents.associate';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='documents.cancel_own';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='documents.reassign';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='cases.manage';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='requirements.edit';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='catalogs.manage';
DELETE FROM role_permissions WHERE role_id='library_manager' AND permission_key='templates.manage';
DELETE FROM schema_migrations WHERE name='0003_managed_organization.up.sql';
