import { test, expect, type Page } from '@playwright/test';
import { resolve } from 'node:path';
async function request(page:Page,method:string,path:string,data:unknown,revision?:number){
 const session=await(await page.request.get('/api/v1/auth/session')).json();
 const response=await page.request.fetch(`/api/v1${path}`,{method,headers:{Origin:'http://127.0.0.1:8099','X-CSRF-Token':session.csrf_token,...(revision?{'If-Match':`"${revision}"`}:{})},data});
 expect(response.ok(),await response.text()).toBeTruthy();return response.status()===204?null:response.json();
}
async function toggle(page:Page,title:string){const accordion=page.locator('details.document-accordion').filter({has:page.locator(':scope > summary').filter({hasText:title})}).first();await accordion.locator(':scope > summary').click();await expect(accordion).toHaveAttribute('open','');await accordion.locator(':scope > summary').click();await expect(accordion).not.toHaveAttribute('open','');await accordion.locator(':scope > summary').click();return accordion}
test('fase 6: herencia, seis acordeones e historial de cargas adaptable',async({page})=>{
 test.setTimeout(150_000);
 await page.goto('/login');await page.getByLabel('Usuario',{exact:true}).fill('admin-e2e');await page.getByLabel('Contraseña',{exact:true}).fill('Browser-fixture-password-2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.getByRole('link',{name:'Bibliotecas',exact:true}).click();await page.getByRole('button',{name:'Nueva biblioteca'}).click();await page.getByLabel('Nombre de la biblioteca').fill('Configuración fase 6');await page.getByLabel('Modalidad de biblioteca').selectOption('managed');await page.getByLabel('Asignarme como gestor de esta biblioteca').check();await page.getByRole('button',{name:'Crear biblioteca',exact:true}).click();
 const libraries=await(await page.request.get('/api/v1/libraries')).json();const library=libraries.items.find((item:{name:string})=>item.name==='Configuración fase 6');
 await page.getByRole('tab',{name:'Cargas',exact:true}).click();await expect(page.getByText('Todavía no has realizado cargas en esta biblioteca.')).toBeVisible();await expect(page.getByText('Selecciona una carga para consultar sus archivos.')).toBeVisible();await expect(page.getByText('Mis lotes',{exact:true})).toHaveCount(0);
 const empty=await request(page,'POST',`/libraries/${library.id}/upload-batches`,{client_batch_id:crypto.randomUUID()});
 await page.getByRole('button',{name:'Actualizar historial',exact:true}).click();await page.getByRole('button',{name:`Seleccionar carga ${empty.id}`,exact:true}).click();await expect(page.getByText('Esta carga no contiene archivos.')).toBeVisible();
 await page.getByRole('tab',{name:'Configuración',exact:true}).click();await page.getByLabel('Heredar formatos de indexación',{exact:true}).uncheck();for(const format of ['DOCX','XLSX','TXT','CSV'])await page.getByLabel(`Indexar ${format}`,{exact:true}).check();await page.getByRole('button',{name:'Guardar reglas de archivos'}).click();await expect(page.getByText(/^Reglas guardadas\./)).toBeVisible();
 await page.getByLabel('Heredar procesamiento automático',{exact:true}).uncheck();await page.getByLabel('Procesamiento automático',{exact:true}).uncheck();await page.getByLabel('Heredar máximo de páginas por pdf',{exact:true}).uncheck();await page.getByLabel('Máximo de páginas por PDF',{exact:true}).fill('40');await page.getByRole('button',{name:'Guardar configuración avanzada'}).click();await expect(page.getByText(/^Configuración avanzada guardada/)).toBeVisible();
 await page.reload();await page.getByRole('button',{name:/Administrada Configuración fase 6/}).click();await page.getByRole('tab',{name:'Configuración',exact:true}).click();await expect(page.getByLabel('Máximo de páginas por PDF',{exact:true})).toHaveValue('40');await expect(page.getByLabel('Heredar idioma del ocr',{exact:true})).toBeChecked();await expect(page.getByRole('combobox',{name:'Idioma del OCR',exact:true})).toBeDisabled();
 await page.getByRole('tab',{name:'Cargas',exact:true}).click();await page.getByLabel('Archivos',{exact:true}).setInputFiles(['native.pdf','sample.docx','sample.xlsx','sample.txt','sample.csv'].map(file=>resolve(`../testdata/documents/${file}`)));await page.getByRole('button',{name:'Guardar borradores',exact:true}).click();await expect(page.getByText('Borrador guardado',{exact:false})).toHaveCount(5);
 const history=page.getByRole('table',{name:'Historial de cargas',exact:true}),files=page.getByRole('table',{name:'Archivos de la carga',exact:true});await expect(files.getByRole('row')).toHaveCount(6);await expect(history.locator('tr.selected-row').getByRole('cell').last()).toHaveText('5');
 for(const [filename,format] of [['native.pdf','PDF'],['sample.docx','DOCX'],['sample.xlsx','XLSX'],['sample.txt','TXT'],['sample.csv','CSV']]){const row=files.getByRole('row').filter({hasText:filename});await expect(row.getByRole('cell').nth(2)).toHaveText(format);await expect(row.getByRole('cell').nth(3)).toContainText(/B/);await expect(row).toContainText('Pausado');}
 const category=await request(page,'POST',`/libraries/${library.id}/categories`,{name:'Cotizaciones'});const kind=await request(page,'POST',`/libraries/${library.id}/document-types`,{name:'Cotización',category_id:category.id,allows_multiple:true,requires_descriptive_title:false});
 await page.getByRole('tab',{name:'Catálogos',exact:true}).click();await page.getByLabel('Nombre de plantilla').fill('Plantilla registrada');await page.getByLabel('Incluir Cotización').check();await page.getByRole('button',{name:'Crear plantilla',exact:true}).click();await expect(page.getByText('Versión de plantilla creada.')).toBeVisible();await toggle(page,'Plantilla registrada');
 await page.getByRole('tab',{name:'Expedientes',exact:true}).click();await page.getByRole('button',{name:'Nuevo expediente'}).click();await page.getByLabel('Identificador del expediente (Expediente)').fill('F6-001');await page.getByLabel('Plantilla inicial').selectOption({label:'Plantilla registrada · versión 1'});await page.getByRole('button',{name:'Crear expediente',exact:true}).click();
 const edit=await toggle(page,'Editar identificador');await edit.getByLabel('Identificador',{exact:true}).fill('F6-002');await edit.getByRole('button',{name:'Guardar expediente'}).click();await expect(page.getByRole('heading',{name:'F6-002',exact:true})).toBeVisible();
 const requirement=await toggle(page,'Ajustar requisito de este expediente');await requirement.getByLabel('Cantidad requerida').fill('2');await requirement.getByRole('button',{name:'Guardar requisito'}).click();await expect(page.getByText('Requisito actualizado solo en este expediente.')).toBeVisible();
 await page.getByRole('tab',{name:'Cargas',exact:true}).click();await history.getByRole('button').first().click();await files.getByRole('button',{name:'Ver detalles de sample.txt',exact:true}).click();
 const dialog=page.getByRole('dialog');await expect(dialog).toContainText('sample.txt');await toggle(page,'Clasificar o asociar a expediente');await dialog.getByLabel('Expediente de destino').selectOption({label:'F6-002'});await dialog.getByLabel('Categoría del documento').selectOption(category.id);await dialog.getByLabel('Tipo del documento').selectOption(kind.id);
 await toggle(page,'Campos adicionales');await dialog.getByRole('button',{name:'Añadir campo'}).click();await dialog.getByLabel('Campo 1',{exact:true}).fill('Referencia');await dialog.getByLabel('Valor 1',{exact:true}).fill('Fase 6');await dialog.getByRole('button',{name:'Guardar clasificación'}).click();await expect(dialog).toContainText('Expediente F6-002');await toggle(page,'Cancelar mi carga');await dialog.getByLabel('Motivo de cancelación').fill('Prueba de cancelación fase 6');await dialog.getByRole('button',{name:'Cancelar carga y conservar evidencia',exact:true}).click();await expect(dialog).toContainText('Cancelado');await dialog.getByRole('button',{name:'Cerrar ficha'}).click();
 const selected=await history.locator('tr.selected-row button').getAttribute('aria-label');await page.getByRole('button',{name:`Seleccionar carga ${empty.id}`,exact:true}).click();await expect(files.getByRole('row')).toHaveCount(1);await page.getByRole('button',{name:selected!,exact:true}).click();await expect(files.getByRole('row')).toHaveCount(6);
 await page.setViewportSize({width:1800,height:1000});const panels=page.locator('.upload-history-layout > section');const a=await panels.nth(0).boundingBox(),b=await panels.nth(1).boundingBox();expect(Math.abs(a!.y-b!.y)).toBeLessThan(2);expect(b!.x).toBeGreaterThan(a!.x+a!.width);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v2-phase6-history-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});const mobileA=await panels.nth(0).boundingBox(),mobileB=await panels.nth(1).boundingBox();expect(mobileB!.y).toBeGreaterThan(mobileA!.y+mobileA!.height);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/v2-phase6-history-mobile.png',fullPage:true});
 await page.getByRole('tab',{name:'Configuración',exact:true}).click();await page.getByLabel('Heredar procesamiento automático',{exact:true}).check();await page.getByRole('button',{name:'Guardar configuración avanzada'}).click();await expect(page.getByText(/^Configuración avanzada guardada/)).toBeVisible();
 await expect.poll(async()=> (await(await page.request.get(`/api/v1/libraries/${library.id}/processing`)).json()).stats.processed).toBe(4);
 await page.goto('/admin/advanced');await expect(page.getByRole('heading',{name:'Configuración avanzada',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Secciones de configuración'})).toBeVisible();
 const documents=await(await page.request.get(`/api/v1/libraries/${library.id}/explorer`)).json();
 for(const item of documents.items){const document=await(await page.request.get(`/api/v1/documents/${item.id}`)).json();await request(page,'POST',`/documents/${item.id}/remove-index`,{reason:'Fin de fixture fase 6',expected_case_id:document.case_id},document.revision)}
});
