import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';

test('extractores: habilitar contenido, buscar en Office y consultar contexto y versión', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill('admin-e2e');
  await page.getByLabel('Contraseña', { exact: true }).fill('Browser-fixture-password-2026');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click();
  await page.getByRole('button', { name: 'Nueva biblioteca' }).click();
  await page.getByLabel('Nombre de la biblioteca').fill('Extractores fase 2');
  await page.getByLabel('Modalidad de biblioteca').selectOption('managed');
  await page.getByLabel('Asignarme como gestor de esta biblioteca').check();
  await page.getByRole('button', { name: 'Crear biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Configuración', exact: true }).click();
  await page.getByLabel('Heredar formatos de indexación', { exact: true }).uncheck();
  for (const format of ['DOCX', 'XLSX', 'TXT', 'CSV']) await page.getByLabel(`Indexar ${format}`, { exact: true }).check();
  await page.getByRole('button', { name: 'Guardar reglas de archivos' }).click();
  await expect(page.getByText(/^Reglas guardadas\./)).toBeVisible();
  await page.getByRole('tab', { name: 'Cargas', exact: true }).click();
  await page.getByLabel('Archivos', { exact: true }).setInputFiles(['docx', 'xlsx', 'txt', 'csv'].map(format => resolve(`../testdata/documents/sample.${format}`)));
  await page.getByRole('button', { name: 'Guardar borradores', exact: true }).click();
  await expect(page.getByText('Borrador guardado', { exact: false })).toHaveCount(4);
  const libraries = await (await page.request.get('/api/v1/libraries')).json();
  const library = libraries.items.find((item: { name: string }) => item.name === 'Extractores fase 2');
  await expect.poll(async () => (await (await page.request.get(`/api/v1/libraries/${library.id}/processing`)).json()).stats.processed).toBe(4);
  await page.getByRole('button', { name: 'Clasificar sample.xlsx', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('region', { name: 'Vista previa del documento' })).toBeVisible();
  await expect(dialog.locator('.retained-text pre')).toContainText('Material sintético');
  await expect(dialog.getByText('Hoja Prueba · celda A1', { exact: true })).toBeVisible();
  await dialog.getByLabel('Unidad de texto').fill('2');
  await expect(dialog.locator('.retained-text pre')).toContainText('12');
  await expect(dialog.getByText('Hoja Prueba · celda B1', { exact: true })).toBeVisible();
  await dialog.getByText('Último procesamiento · Completado', { exact: true }).click();
  await expect(dialog).toContainText('xlsx-openxml · versión 1');
  await expect(dialog).toContainText('Celdas con contenido o fórmula');
  await page.screenshot({ path: 'test-results/v2-phase2-xlsx.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.getByRole('link', { name: 'Buscar documentos', exact: true }).click();
  await page.getByLabel('Texto a buscar').fill('"Material sintético"');
  await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click();
  await expect(page.getByRole('heading', { name: '1 documento encontrado' })).toBeVisible();
  await expect(page.locator('.snippet')).toContainText('Hoja Prueba · celda A1');
  await page.locator('.snippet').click();
  await expect(dialog.locator('.retained-text pre')).toContainText('Material sintético');
  await expect(dialog.getByRole('link', { name: 'Descargar XLSX', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
