import { test, expect } from '@playwright/test';
import { mkdtemp, copyFile, mkdir, utimes, rm, realpath } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

test('búsqueda agrupada independiente, navegación, PDF ampliado y recursos',async({page})=>{
 const directory=await realpath(await mkdtemp(join(tmpdir(),'aibid-r4-browser-')));
 try{
  for(const library of ['A','B']){
   await mkdir(join(directory,library,'Subcarpeta'),{recursive:true});
   for(let i=0;i<13;i++){const path=join(directory,library,i===12?'Subcarpeta/R4-sub.pdf':`R4-${i}.pdf`);await copyFile(resolve('../testdata/documents/native.pdf'),path);const past=new Date(Date.now()-10000);await utimes(path,past,past);}
  }
  await page.goto('/login');await page.getByLabel('Usuario',{exact:true}).fill('admin-e2e');await page.getByLabel('Contraseña',{exact:true}).fill('Browser-fixture-password-2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();
  for(const name of ['A','B']){
   await page.getByRole('link',{name:'Bibliotecas',exact:true}).click();await page.getByRole('button',{name:'Nueva biblioteca'}).click();await page.getByLabel('Nombre de la biblioteca').fill(`Navegación R4 ${name}`);await page.getByLabel('Asignarme como gestor').check();await page.getByRole('button',{name:'Crear biblioteca',exact:true}).click();await page.getByRole('tab',{name:'Carpetas',exact:true}).click();await page.getByLabel('Ruta de la carpeta en el servidor').fill(join(directory,name));await page.getByRole('button',{name:'Inspeccionar carpeta'}).click();await page.getByRole('button',{name:'Registrar e indexar'}).click();await page.getByRole('tab',{name:'Procesamiento',exact:true}).click();await expect(page.locator('.metric').filter({hasText:'Procesados'}).locator('strong')).toHaveText('13',{timeout:30000});await page.getByRole('button',{name:'Todas las bibliotecas',exact:false}).click();
  }
  await page.getByRole('link',{name:'Buscar documentos',exact:true}).click();await page.getByLabel('Texto a buscar').fill('R4-');await page.getByRole('button',{name:'Buscar documentos',exact:true}).click();
  const first=page.getByRole('region',{name:'Resultados de Navegación R4 A',exact:true});const second=page.getByRole('region',{name:'Resultados de Navegación R4 B',exact:true});
  await expect(first.locator('.document-row')).toHaveCount(10);await expect(second.locator('.document-row')).toHaveCount(10);await expect(first.getByText('13 coincidencias')).toBeVisible();
  await first.getByRole('button',{name:'Siguiente',exact:true}).click();await expect(first.locator('.document-row')).toHaveCount(3);await expect(second.locator('.document-row')).toHaveCount(10);
  await second.getByLabel('Resultados por página').selectOption('25');await expect(second.locator('.document-row')).toHaveCount(13);await expect(first.locator('.document-row')).toHaveCount(3);
  await second.locator('.search-results-scroll').evaluate(element=>element.scrollTop=100);await first.getByRole('button',{name:'Anterior',exact:true}).click();await expect(first.locator('.document-row')).toHaveCount(10);expect(await second.locator('.search-results-scroll').evaluate(element=>element.scrollTop)).toBe(100);
  await second.getByRole('button',{name:'Contraer resultados'}).click();await expect(second.locator('.document-row').first()).not.toBeVisible();await second.getByRole('button',{name:'Expandir resultados'}).click();await expect(second.locator('.document-row')).toHaveCount(13);
  await page.screenshot({path:'test-results/r4-grouped-search.png',fullPage:true});
  await first.getByRole('button',{name:'Ver ficha',exact:true}).first().click();const frame=page.locator('iframe[title="Vista previa del PDF"]');const original=await frame.elementHandle();await frame.evaluate(element=>(element as HTMLElement).dataset.testIdentity='same-viewer');const source=await frame.getAttribute('src');
  await expect.poll(async()=>{const viewer=page.frames().find(frame=>frame.url().startsWith('chrome-extension://'));if(!viewer)return 0;return viewer.locator('pdf-viewer').evaluate(element=>(element as HTMLElement & {loadProgress_:number}).loadProgress_).catch(()=>0);}).toBe(100);
  await page.getByRole('button',{name:'Ampliar PDF',exact:true}).click();await expect(page.locator('.document-dialog')).toHaveClass(/pdf-expanded/);expect(await frame.getAttribute('src')).toBe(source);expect(await original?.evaluate(element=>element.isConnected)).toBeTruthy();await expect(page.locator('.retained-text')).not.toBeVisible();await page.screenshot({path:'test-results/r4-expanded-pdf.png',fullPage:true});
  await page.getByRole('button',{name:'Volver a vista dividida'}).click();await expect(frame).toHaveAttribute('data-test-identity','same-viewer');await expect(page.locator('.retained-text')).toBeVisible();await page.getByRole('button',{name:'Cerrar ficha'}).click();
  await page.getByRole('link',{name:'Bibliotecas',exact:true}).click();await page.getByRole('button',{name:/Navegación R4 A/}).click();await page.getByRole('button',{name:'Explorador de archivos',exact:true}).click();await expect(page.locator('.file-tile')).toHaveCount(13);await page.getByRole('button',{name:'Subcarpeta Carpeta',exact:true}).click();await expect(page.locator('.file-tile')).toHaveCount(1);
  await page.getByRole('button',{name:'Vista de lista',exact:true}).click();await expect(page.getByRole('button',{name:'R4-sub.pdf',exact:true})).toBeVisible();await page.getByLabel('Buscar en esta biblioteca').fill('PR-008');await page.getByRole('combobox',{name:'Ámbito',exact:true}).selectOption('folder');await page.getByRole('button',{name:'Buscar en biblioteca',exact:true}).click();await expect(page.locator('.search-library-section .document-row')).toHaveCount(1);
  await page.getByRole('combobox',{name:'Disponibilidad',exact:true}).selectOption('missing');await expect(page.getByText('No hay coincidencias con estos filtros.')).toBeVisible();await page.getByRole('combobox',{name:'Disponibilidad',exact:true}).selectOption('');await expect(page.locator('.search-library-section .document-row')).toHaveCount(1);
  await page.getByRole('button',{name:'Cerrar búsqueda',exact:true}).click();await page.getByRole('button',{name:'Explorador de archivos',exact:true}).click();await expect(page.locator('.file-tile')).toHaveCount(1);await page.getByRole('button',{name:'Carpeta superior',exact:false}).click();await expect(page.locator('.file-tile')).toHaveCount(13);await page.screenshot({path:'test-results/r4-file-explorer.png',fullPage:true});
  await page.getByRole('link',{name:'Procesamiento',exact:true}).click();await expect(page.getByRole('heading',{name:'Recursos detectados al iniciar'})).toBeVisible();await page.getByLabel('Modo de procesamiento').selectOption('manual');await page.getByLabel('Máximo de extracción directa').fill('2');await page.getByLabel('Máximo de OCR').fill('1');await page.getByLabel('Límite general de contenido').fill('2');await page.getByRole('button',{name:'Guardar procesamiento'}).click();await expect(page.getByText('Configuración guardada.',{exact:false})).toBeVisible();await page.reload();await expect(page.getByLabel('Máximo de extracción directa')).toHaveValue('2');await page.getByLabel('Modo de procesamiento').selectOption('auto');await page.getByRole('button',{name:'Guardar procesamiento'}).click();await expect(page.getByText('Configuración guardada.',{exact:false})).toBeVisible();
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 }finally{await rm(directory,{recursive:true,force:true});}
});
