import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';

test('H4: catálogo, plantilla, expediente y carga múltiple privada con clasificación', async ({ page }) => {
  await page.goto('/login'); await page.getByLabel('Usuario', { exact: true }).fill('admin-e2e'); await page.getByLabel('Contraseña', { exact: true }).fill('Browser-fixture-password-2026'); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click(); await page.getByRole('button', { name: 'Nueva biblioteca' }).click();
  await page.getByLabel('Nombre de la biblioteca').fill('Organización H4'); await page.getByLabel('Modalidad de biblioteca').selectOption('hybrid'); await page.getByLabel('Asignarme como gestor de esta biblioteca').check(); await page.getByRole('button', { name: 'Crear biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Catálogos', exact: true }).click(); await page.getByLabel('Nombre de categoría').fill('Planos'); await page.getByRole('button', { name: 'Crear categoría', exact: true }).click();
  await page.getByLabel('Categoría del tipo').selectOption({ label: 'Planos' }); await page.getByLabel('Nombre del tipo').fill('Plano general'); await page.getByLabel('Exige título descriptivo (por ejemplo, Varios)').check(); await page.getByRole('button', { name: 'Crear tipo', exact: true }).click();
  await page.getByLabel('Nombre de plantilla').fill('Ingreso inicial'); await page.getByLabel('Incluir Plano general').check(); await page.getByRole('button', { name: 'Crear plantilla', exact: true }).click(); await expect(page.getByText('Versión de plantilla creada.')).toBeVisible();
  await page.getByRole('tab', { name: 'Expedientes', exact: true }).click(); await page.getByRole('button', { name: 'Nuevo expediente' }).click(); await page.getByLabel('Identificador del expediente (Expediente)').fill('PR-H4'); await page.getByLabel('Plantilla inicial').selectOption({ label: 'Ingreso inicial · versión 1' }); await page.getByRole('button', { name: 'Crear expediente', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'PR-H4', exact: true })).toBeVisible(); await expect(page.getByText('0 aprobados válidos')).toBeVisible(); await expect(page.getByRole('progressbar', { name: 'Avance del expediente' })).toHaveAttribute('value', '0');
  await page.getByRole('tab', { name: 'Cargas', exact: true }).click(); await page.getByLabel('Archivos PDF', { exact: true }).setInputFiles([resolve('../testdata/documents/native.pdf'), resolve('../testdata/documents/scanned.pdf')]); await page.getByRole('button', { name: 'Guardar borradores' }).click(); await expect(page.getByText(/Borrador guardado/)).toHaveCount(2);
  await page.getByRole('button', { name: 'Clasificar native.pdf', exact: true }).click(); const dialog = page.getByRole('dialog'); await expect(dialog).toContainText('Temporal privado'); await expect(dialog).not.toContainText('Ruta original:');
  await dialog.getByText('Clasificar o asociar a expediente', { exact: true }).click(); await dialog.getByLabel('Expediente de destino').selectOption({ label: 'PR-H4' }); await dialog.getByLabel('Categoría del documento').selectOption({ label: 'Planos' }); await dialog.getByLabel('Tipo del documento').selectOption({ label: 'Plano general' }); await dialog.getByLabel('Título descriptivo', { exact: true }).fill('Plano de cubierta'); await dialog.getByRole('button', { name: 'Guardar clasificación' }).click(); await expect(dialog).toContainText('Expediente PR-H4');
  await page.screenshot({ path: 'test-results/h4-private-document.png', fullPage: true }); await dialog.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.getByRole('tab', { name: 'Expedientes', exact: true }).click(); await page.getByRole('button', { name: /PR-H4/ }).click(); await expect(page.getByText(/1 borradores/)).toBeVisible(); await expect(page.getByRole('button', { name: 'Plano de cubierta', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/h4-case.png', fullPage: true });
  await page.getByRole('link', { name: 'Buscar documentos', exact: true }).click(); await page.getByLabel('Texto a buscar').fill('PR-H4'); await page.getByRole('combobox', { name: 'Buscar en', exact: true }).selectOption('identifier'); await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click(); await expect(page.getByRole('heading', { name: '1 documento encontrado', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Biblioteca', exact: true }).selectOption({ label: 'Organización H4' });
  await page.getByRole('combobox', { name: 'Categoría', exact: true }).selectOption({ label: 'Planos' });
  await page.getByRole('combobox', { name: 'Tipo de documento', exact: true }).selectOption({ label: 'Plano general' });
  await page.getByRole('combobox', { name: 'Expediente', exact: true }).selectOption({ label: 'PR-H4' });
  await page.getByRole('combobox', { name: 'Origen', exact: true }).selectOption('managed');
  await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click(); await expect(page.getByRole('heading', { name: '1 documento encontrado', exact: true })).toBeVisible();
  await page.getByLabel('Sin expediente asignado').check(); await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click(); await expect(page.getByRole('heading', { name: '0 documentos encontrados', exact: true })).toBeVisible();
  await page.getByLabel('Sin expediente asignado').uncheck(); await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click(); await expect(page.getByRole('heading', { name: '1 documento encontrado', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await page.screenshot({ path: 'test-results/h4-search-mobile.png', fullPage: true });
});
