import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';

test('fase 3: pausa persistente, límites, Word con párrafos vacíos y Excel con impresión', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill('admin-e2e');
  await page.getByLabel('Contraseña', { exact: true }).fill('Browser-fixture-password-2026');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('link', { name: 'Ajustes', exact: true }).click(); await page.getByRole('navigation', { name: 'Secciones de configuración' }).getByRole('link', { name: 'Procesamiento y recursos', exact: true }).click();
  await page.getByLabel('Máximo de intentos', { exact: true }).fill('2');
  await page.getByLabel('Espera inicial entre intentos (segundos)', { exact: true }).fill('3');
  await page.getByLabel('Tiempo máximo por documento (segundos)', { exact: true }).fill('30');
  await page.getByRole('button', { name: 'Guardar límites de procesamiento' }).click();
  await expect.poll(async () => (await (await page.request.get('/api/v1/system/processing-policy')).json()).maximum_attempts).toBe(2);
  await page.getByRole('button', { name: 'Pausar procesamiento', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reanudar procesamiento', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Reanudar procesamiento', exact: true })).toBeVisible();
  await expect(page.getByLabel('Tiempo máximo por documento (segundos)')).toHaveValue('30');
  await page.screenshot({ path: 'test-results/v2-phase3-policy.png', fullPage: true });
  await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click();
  await page.getByRole('button', { name: 'Nueva biblioteca' }).click();
  await page.getByLabel('Nombre de la biblioteca').fill('Robustez fase 3');
  await page.getByLabel('Modalidad de biblioteca').selectOption('managed');
  await page.getByLabel('Asignarme como gestor de esta biblioteca').check();
  await page.getByRole('button', { name: 'Crear biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Configuración', exact: true }).click();
  await page.getByLabel('Heredar formatos de indexación', { exact: true }).uncheck();
  for (const format of ['DOCX', 'XLSX']) await page.getByLabel(`Indexar ${format}`, { exact: true }).check();
  await page.getByRole('button', { name: 'Guardar reglas de archivos' }).click();
  await expect(page.getByText(/^Reglas guardadas\./)).toBeVisible();
  await page.getByRole('tab', { name: 'Cargas', exact: true }).click();
  await page.getByLabel('Archivos', { exact: true }).setInputFiles(['blank-leading.docx', 'printer-settings.xlsx'].map(name => resolve(`../testdata/documents/${name}`)));
  await page.getByRole('button', { name: 'Guardar borradores', exact: true }).click();
  await expect(page.getByText('Borrador guardado', { exact: false })).toHaveCount(2);
  const library = (await (await page.request.get('/api/v1/libraries')).json()).items.find((value: { name: string }) => value.name === 'Robustez fase 3');
  await page.getByRole('tab', { name: 'Procesamiento', exact: true }).click();
  await expect(page.getByText(/^Procesamiento pausado por un administrador/)).toBeVisible();
  let jobs = (await (await page.request.get(`/api/v1/libraries/${library.id}/jobs`)).json()).items;
  expect(jobs.filter((job: { job_type: string }) => job.job_type === 'extract').every((job: { attempt_count: number }) => job.attempt_count === 0)).toBeTruthy();
  await page.goto('/admin/processing');
  await page.getByRole('button', { name: 'Reanudar procesamiento', exact: true }).click();
  await expect.poll(async () => (await (await page.request.get(`/api/v1/libraries/${library.id}/processing`)).json()).stats.processed).toBe(2);
  jobs = (await (await page.request.get(`/api/v1/libraries/${library.id}/jobs`)).json()).items;
  expect(jobs.filter((job: { job_type: string }) => job.job_type === 'extract').every((job: { maximum_attempts: number }) => job.maximum_attempts === 2)).toBeTruthy();
  await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click();
  await page.getByRole('button', { name: /Robustez fase 3/ }).click();
  await page.getByRole('tab', { name: 'Documentos', exact: true }).click();
  await expect(page.locator('svg.file-icon[data-format="docx"]')).toBeVisible();
  await expect(page.locator('svg.file-icon[data-format="xlsx"]')).toBeVisible();
  await page.getByRole('button', { name: 'blank-leading.docx', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('.retained-text pre')).toContainText('Cotizacion sintetica');
  await expect(dialog.getByText('Documento · párrafo 3', { exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Siguiente', exact: true }).click();
  await expect(dialog.locator('.retained-text pre')).toContainText('Instalacion sintetica');
  await page.screenshot({ path: 'test-results/v2-phase3-word.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  // Restore shared test-server defaults for subsequent cases.
  await page.goto('/admin/processing');
  await page.getByLabel('Máximo de intentos', { exact: true }).fill('5');
  await page.getByLabel('Espera inicial entre intentos (segundos)', { exact: true }).fill('2');
  await page.getByLabel('Tiempo máximo por documento (segundos)', { exact: true }).fill('3600');
  await page.getByRole('button', { name: 'Guardar límites de procesamiento' }).click();
  await expect.poll(async () => (await (await page.request.get('/api/v1/system/processing-policy')).json()).maximum_attempts).toBe(5);
});
