import { test, expect } from '@playwright/test';
import { mkdtemp, readFile, writeFile, mkdir, utimes, rm, realpath } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

test('intervalos, páginas acotadas, vistas y confirmación sin borrar originales', async ({ page }) => {
  const directory = await realpath(await mkdtemp(join(tmpdir(), 'aibid-r6-')));
  const original = await readFile(resolve('../testdata/documents/native.pdf'));
  try {
    // One item beyond the page boundary; no volume or load test.
    for (let n = 0; n < 51; n++) {
      const folder = join(directory, `Carpeta-${String(n).padStart(2, '0')}`);
      await mkdir(folder);
      const file = join(folder, 'Ejemplo.pdf');
      await writeFile(file, n < 30 ? original : Buffer.concat([original, Buffer.from('\n% Segundo grupo de prueba\n')]));
      const past = new Date(Date.now() - 10000); await utimes(file, past, past);
    }
    await page.goto('/login'); await page.getByLabel('Usuario', { exact: true }).fill('admin-e2e');
    await page.getByLabel('Contraseña', { exact: true }).fill('Browser-fixture-password-2026');
    await page.getByRole('button', { name: 'Entrar', exact: true }).click();
    await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click();
    await page.getByRole('button', { name: 'Nueva biblioteca' }).click();
    await page.getByLabel('Nombre de la biblioteca').fill('Revisión R6');
    await page.getByLabel('Asignarme como gestor').check();
    await page.getByRole('button', { name: 'Crear biblioteca', exact: true }).click();
    await page.getByRole('tab', { name: 'Carpetas', exact: true }).click();
    await page.getByLabel('Ruta de la carpeta en el servidor').fill(directory);
    await page.getByRole('button', { name: 'Inspeccionar carpeta' }).click();
    await page.getByRole('button', { name: 'Registrar e indexar' }).click();
    await page.getByText('Configurar carpeta', { exact: true }).click();
    await expect(page.getByLabel('Comprobar cada', { exact: true })).toHaveValue('1');
    await expect(page.getByLabel('Unidad del intervalo')).toHaveValue('86400');
    await page.getByLabel('Unidad del intervalo').selectOption('3600');
    await expect(page.getByLabel('Comprobar cada', { exact: true })).toHaveValue('24');
    await page.getByLabel('Unidad del intervalo').selectOption('60');
    await page.getByLabel('Comprobar cada', { exact: true }).fill('30');
    await page.getByLabel('Unidad del intervalo').selectOption('1');
    await expect(page.getByLabel('Comprobar cada', { exact: true })).toHaveValue('1800');
    await page.getByRole('button', { name: 'Guardar verificación' }).click();
    await expect(page.getByText('Configuración de vigilancia guardada.', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Comprobar cada', { exact: true })).toHaveValue('30');
    await expect(page.getByLabel('Unidad del intervalo')).toHaveValue('60');
    await page.getByRole('tab', { name: 'Procesamiento', exact: true }).click();
    await expect(page.locator('.metric').filter({ hasText: 'Procesados' }).locator('strong')).toHaveText('51', { timeout: 30000 });
    await page.getByRole('tab', { name: 'Duplicados', exact: true }).click();
    await expect(page.locator('.duplicate-groups tbody tr')).toHaveCount(2);
    await page.locator('.duplicate-groups tbody tr').last().getByRole('button').click();
    await expect(page.locator('.duplicate-groups tbody tr').last()).toHaveClass('selected-row');
    await expect(page.locator('.duplicate-file').first()).toBeVisible();
    await page.getByText('Ver huella completa del grupo', { exact: true }).click();
    await expect(page.locator('.document-accordion[open]')).toContainText('SHA-256:');
    await page.screenshot({ path: 'test-results/r6-duplicates.png', fullPage: true });
    await page.getByRole('tab', { name: 'Documentos', exact: true }).click();
    await page.getByRole('button', { name: 'Vista de cuadrícula', exact: true }).click();
    await expect(page.locator('.folder-tile')).toHaveCount(50);
    await page.getByRole('navigation', { name: 'Carpetas', exact: true }).getByRole('button', { name: 'Siguiente' }).click();
    await expect(page.locator('.folder-tile')).toHaveCount(1);
    await page.getByRole('button', { name: 'Vista de lista', exact: true }).click();
    await expect(page.locator('.explorer-details tbody tr')).toHaveCount(1);
    await page.getByRole('button', { name: 'Carpeta-50', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Ejemplo.pdf', exact: true })).toBeVisible();
    await expect(page.getByRole('columnheader', { name: 'Tamaño', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Ejemplo.pdf', exact: true }).click();
    await page.getByText('Huella y trazabilidad', { exact: true }).click();
    await page.getByText('Retirar del índice', { exact: true }).click();
    await expect(page.locator('.document-accordion[open]')).toHaveCount(2);
    await page.getByRole('button', { name: 'Consultar historial', exact: true }).click();
    await expect(page.getByRole('table', { name: 'Historial del documento' })).toContainText('Documento detectado');
    await page.getByRole('table', { name: 'Historial del documento' }).getByRole('button', { name: 'Ver detalles' }).first().click();
    await page.getByText('Información avanzada · registro original', { exact: true }).click();
    await expect(page.locator('.audit-dialog .document-accordion[open]')).toContainText('event_type');
    await page.getByRole('button', { name: 'Cerrar detalle', exact: true }).click();
    await page.screenshot({ path: 'test-results/r6-document-history.png', fullPage: true });
    await page.getByLabel('Motivo', { exact: true }).fill('Prueba del retiro');
    await page.getByRole('button', { name: 'Confirmar retiro del índice', exact: true }).click();
    await expect(page.getByRole('dialog').first()).toBeVisible();
    await page.getByLabel('Confirmo que se retirará del índice de AIBID.', { exact: false }).check();
    await page.getByRole('button', { name: 'Confirmar retiro del índice', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    expect(await readFile(join(directory, 'Carpeta-50', 'Ejemplo.pdf'))).toEqual(Buffer.concat([original, Buffer.from('\n% Segundo grupo de prueba\n')]));
    await page.getByRole('button', { name: 'Vista de cuadrícula', exact: true }).click();
    await page.getByRole('button', { name: 'Carpeta superior', exact: false }).click();
    await expect(page.getByRole('button', { name: 'Vista de cuadrícula' })).toHaveAttribute('aria-pressed', 'true');
    await page.locator('.folder-tile').first().hover();
    await page.screenshot({ path: 'test-results/r6-explorer-hover.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  } finally { await rm(directory, { recursive: true, force: true }); }
});
