import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';

test('fase 5: filtros por formato, contexto y reindexación sin duplicados', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill('admin-e2e');
  await page.getByLabel('Contraseña', { exact: true }).fill('Browser-fixture-password-2026');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('link', { name: 'Bibliotecas', exact: true }).click();
  await page.getByRole('button', { name: 'Nueva biblioteca' }).click();
  await page.getByLabel('Nombre de la biblioteca').fill('Búsqueda fase 5');
  await page.getByLabel('Modalidad de biblioteca').selectOption('managed');
  await page.getByLabel('Asignarme como gestor de esta biblioteca').check();
  await page.getByRole('button', { name: 'Crear biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Configuración', exact: true }).click();
  await page.getByLabel('Heredar formatos de indexación', { exact: true }).uncheck();
  for (const format of ['DOCX', 'XLSX', 'TXT', 'CSV']) await page.getByLabel(`Indexar ${format}`, { exact: true }).check();
  await page.getByRole('button', { name: 'Guardar reglas de archivos' }).click();
  await expect(page.getByText(/^Reglas guardadas\./)).toBeVisible();
  await page.getByRole('tab', { name: 'Cargas', exact: true }).click();
  await page.getByLabel('Archivos', { exact: true }).setInputFiles(['docx', 'xlsx', 'txt', 'csv'].map(format => resolve(`../testdata/documents/sample.${format}`)));
  await page.getByRole('button', { name: 'Guardar borradores', exact: true }).click();
  await expect(page.getByText('Borrador guardado', { exact: false })).toHaveCount(4);
  const libraries = await (await page.request.get('/api/v1/libraries')).json();
  const library = libraries.items.find((item: { name: string }) => item.name === 'Búsqueda fase 5');
  await expect.poll(async () => (await (await page.request.get(`/api/v1/libraries/${library.id}/processing`)).json()).stats.processed).toBe(4);
  await page.getByRole('tab', { name: 'Documentos', exact: true }).click();
  await expect(page.getByLabel('Formato de archivo')).toHaveValue('');
  await page.getByLabel('Formato de archivo').selectOption('xlsx');
  await expect(page.getByRole('button', { name: 'sample.xlsx', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'sample.docx', exact: true })).toHaveCount(0);
  await page.getByLabel('Buscar en esta biblioteca').fill('"Material sintético"');
  await page.getByRole('button', { name: 'Buscar en biblioteca', exact: true }).click();
  await expect(page.locator('.snippet').first()).toContainText('Hoja Prueba');
  await expect(page.locator('.document-badges').getByText('XLSX', { exact: true })).toBeVisible();
  await page.getByLabel('Formato de archivo').selectOption('docx');
  await expect(page.getByText('No hay coincidencias con estos filtros.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar búsqueda', exact: true }).click();
  await page.getByLabel('Formato de archivo').selectOption('txt');
  await page.getByRole('button', { name: 'sample.txt', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('.retained-text pre')).toContainText('cambios');
  const documents = await (await page.request.get(`/api/v1/libraries/${library.id}/explorer?format=txt`)).json();
  const id = documents.items[0].id;
  const before = await (await page.request.get(`/api/v1/documents/${id}`)).json();
  await dialog.getByRole('button', { name: 'Reindexar documento', exact: true }).click();
  await expect(dialog.getByText('Reindexación completada. La ficha y el texto están actualizados.', { exact: true })).toBeVisible();
  const after = await (await page.request.get(`/api/v1/documents/${id}`)).json();
  expect(after.id).toBe(before.id);
  expect(after.sha256).toBe(before.sha256);
  expect(after.processing.id).not.toBe(before.processing.id);
  await expect(dialog.locator('.retained-text pre')).toContainText('cambios');
  await dialog.getByText('Huella y trazabilidad', { exact: true }).click();
  await dialog.getByRole('button', { name: 'Consultar historial' }).click();
  await expect(dialog.getByRole('table', { name: 'Historial del documento' })).toContainText('Reindexación solicitada');
  await page.screenshot({ path: 'test-results/v2-phase5-reindex.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.getByRole('link', { name: 'Buscar documentos', exact: true }).click();
  await expect(page.getByLabel('Formato de archivo')).toHaveValue('');
  await page.getByRole('combobox', { name: 'Biblioteca', exact: true }).selectOption(library.id);
  await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click();
  await expect(page.getByRole('heading', { name: '4 documentos encontrados' })).toBeVisible();
  for (const format of ['pdf', 'docx', 'xlsx', 'txt', 'csv']) {
    await page.getByLabel('Formato de archivo').selectOption(format);
    await page.getByRole('button', { name: 'Buscar documentos', exact: true }).click();
    await expect(page.getByRole('heading', { name: format === 'pdf' ? '0 documentos encontrados' : '1 documento encontrado', exact: true })).toBeVisible();
    if (format !== 'pdf') await expect(page.getByRole('button', { name: `sample.${format}`, exact: true })).toBeVisible();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/v2-phase5-filters-mobile.png', fullPage: true });
});
