import { useEffect, useState } from 'react';
import { api, message } from './api';
import { Notice } from './components';
import { Accordion } from './Accordion';

type Policy = {
 automatic_processing:boolean; reprocess_changes:boolean; manual_priority:boolean;
 ocr_enabled:boolean; ocr_automatic:boolean; ocr_languages:string; ocr_minimum_characters:number;
 maximum_pages:number; page_timeout_seconds:number; watcher_enabled:boolean; ignore_office_temporary:boolean;
 ignore_hidden:boolean; ignore_temporary:boolean; ignored_extensions:string[]; preview_enabled:boolean; preview_source_mb:number;
};
type Key=keyof Policy;
type Overrides=Partial<{[K in Key]:Policy[K]|null}>;
interface Configuration {global:Policy;effective:Policy;overrides:Overrides;revision:number;global_revision:number;preview_revision:number}
const labels:Record<Key,string>={automatic_processing:'Procesamiento automático',reprocess_changes:'Reprocesar documentos modificados',manual_priority:'Priorizar trabajos manuales',ocr_enabled:'Habilitar OCR',ocr_automatic:'OCR automático',ocr_languages:'Idioma del OCR',ocr_minimum_characters:'Umbral de texto nativo (caracteres)',maximum_pages:'Máximo de páginas por PDF',page_timeout_seconds:'Tiempo por operación PDF/OCR (segundos)',watcher_enabled:'Vigilancia de cambios en carpetas',ignore_office_temporary:'Ignorar temporales de Office',ignore_hidden:'Ignorar archivos y carpetas ocultos',ignore_temporary:'Ignorar archivos temporales',ignored_extensions:'Extensiones ignoradas',preview_enabled:'Permitir vistas previas en esta biblioteca',preview_source_mb:'Máximo por archivo para vista previa (MiB)'};
const limits:Partial<Record<Key,[number,number]>>={ocr_minimum_characters:[1,10000],maximum_pages:[1,10000],page_timeout_seconds:[5,300],preview_source_mb:[1,512]};
export function AdvancedSettings({libraryID,changed}:{libraryID?:string;changed?:()=>void}){
 const endpoint=libraryID?`/libraries/${libraryID}/advanced-settings`:'/system/advanced';
 const [saved,setSaved]=useState<Configuration|null>(null),[policy,setPolicy]=useState<Policy|null>(null),[overrides,setOverrides]=useState<Overrides>({});
 const [extensionsText,setExtensionsText]=useState('');
 const [error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 function receive(value:Configuration){setSaved(value);setPolicy(value.effective);setOverrides(value.overrides);setExtensionsText(value.effective.ignored_extensions.join(', '))}
 useEffect(()=>{const controller=new AbortController();api<Configuration>(endpoint,{signal:controller.signal}).then(receive).catch(cause=>{if(!controller.signal.aborted)setError(message(cause))});return()=>controller.abort()},[endpoint,revision]);
 function change(key:Key,value:Policy[Key]){setPolicy(previous=>previous&&({...previous,[key]:value}));setOverrides(previous=>({...previous,[key]:value}))}
 function field(key:Key){if(!policy||!saved)return null;const inherited=!!libraryID&&overrides[key]==null;const value=policy[key];return <div className="advanced-field" key={key}>
 {libraryID&&<label className="check"><input type="checkbox" checked={inherited} disabled={busy} onChange={event=>{const inherit=event.target.checked;if(key==='ignored_extensions'&&inherit)setExtensionsText(saved.global.ignored_extensions.join(', '));setOverrides({...overrides,[key]:inherit?null:value});setPolicy({...policy,[key]:inherit?saved.global[key]:value})}}/>Heredar {labels[key].toLowerCase()}</label>}
 <label className={typeof value==='boolean'?'check':''}>
 {typeof value==='boolean'?<><input type="checkbox" disabled={busy||inherited} checked={value} onChange={event=>change(key,event.target.checked)}/>{labels[key]}</>:<>{labels[key]}{typeof value==='number'?<input type="number" required disabled={busy||inherited} min={limits[key]?.[0]} max={limits[key]?.[1]} value={value} onChange={event=>change(key,Number(event.target.value))}/>:key==='ocr_languages'?<select disabled={busy||inherited} value={String(value)} onChange={event=>change(key,event.target.value)}><option value="spa">Español</option><option value="eng">Inglés</option><option value="spa+eng">Español e inglés</option></select>:<input disabled={busy||inherited} value={extensionsText} placeholder=".bak, .log" onChange={event=>{setExtensionsText(event.target.value);change(key,event.target.value.split(',').map(item=>item.trim()).filter(Boolean))}}/>}</>}
 </label>{libraryID&&<small className="muted">{inherited?'Heredado de la instalación':'Excepción de esta biblioteca'}</small>}</div>}
 return <>{!libraryID&&<><header className="page-heading"><p className="eyebrow">CONFIGURACIÓN DE AIBID</p><h2>Configuración avanzada</h2><p>Valores globales y reglas que las bibliotecas pueden heredar.</p></header></>}
 <section className="card"><div className="section-heading"><h2>{libraryID?'Reglas avanzadas de esta biblioteca':'Automatización, OCR y vigilancia'}</h2><button className="secondary" disabled={busy} onClick={()=>{setError('');setSuccess('');setRevision(revision+1)}}>Actualizar configuración avanzada</button></div>
 <Notice text={error}/><Notice text={success} kind="success"/>
 {policy&&saved&&<form className="form-grid" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setSuccess('');try{receive(await api<Configuration>(endpoint,{method:'PUT',body:{global:policy,overrides,revision:saved.revision,global_revision:saved.global_revision,preview_revision:saved.preview_revision}}));setSuccess('Configuración avanzada guardada. Se aplica a los nuevos trabajos; los que ya están en curso conservan sus parámetros.');changed?.()}catch(cause){setError(message(cause))}finally{setBusy(false)}}}>
 <Accordion title="Procesamiento automático" open><div className="editor-grid">{(['automatic_processing','reprocess_changes','manual_priority'] as Key[]).map(field)}</div><p className="muted">Desactivar el procesamiento automático conserva las tareas pendientes. Verificar biblioteca y Reindexar documento permiten solicitar trabajo manual. La pausa general siempre se respeta. La comprobación de integridad de archivos administrados continúa para proteger tus documentos.</p><p className="muted">La prioridad manual se aplica al iniciar el siguiente trabajo; no interrumpe los procesos activos. Los límites de concurrencia, reintentos y tiempo total se comparten entre bibliotecas.</p></Accordion>
 <Accordion title="Reconocimiento de texto (OCR)" open><div className="editor-grid">{(['ocr_enabled','ocr_automatic','ocr_languages','ocr_minimum_characters','maximum_pages','page_timeout_seconds'] as Key[]).map(field)}</div><p className="muted">Solo PDF utiliza OCR. Una página con menos letras o números que el umbral puede requerir reconocimiento. Si desactivas OCR automático, los trabajos manuales aún pueden usarlo; desactivar Habilitar OCR lo impide también en esos trabajos. Los idiomas seleccionados deben estar instalados.</p><p className="muted">Cambiar estas reglas no borra texto existente. Reindexa los documentos que quieras procesar con los nuevos valores.</p></Accordion>
 <Accordion title="Watcher y archivos ignorados" open><div className="editor-grid">{(['watcher_enabled','ignore_office_temporary','ignore_hidden','ignore_temporary','ignored_extensions'] as Key[]).map(field)}</div><p className="muted">La vigilancia detecta cambios; al desactivarla se conserva la verificación periódica configurada en Carpetas. Se ignoran temporales de Office como ~$documento.docx y .~lock.documento#, y temporales .tmp, .temp, .swp o terminados en ~ según las opciones activadas. Separa extensiones por comas.</p><p className="muted">Los nombres con punto inicial y el atributo Oculto de Windows se omiten al activar esa opción. Las carpetas protegidas del sistema y el atributo Sistema de Windows se excluyen siempre. Una omisión por reglas conserva los originales, su historial y cualquier texto previamente indexado.</p></Accordion>
 {libraryID&&<Accordion title="Vistas previas de esta biblioteca" open><div className="editor-grid">{field('preview_enabled')}{field('preview_source_mb')}</div><p className="muted">La desactivación global de vistas previas tiene prioridad. La caché, su limpieza y el conversor se administran una sola vez para toda la instalación.</p></Accordion>}
 <p className="muted">Duplicados: cada archivo conserva su ubicación, registro e historial. La comparación por contenido y la revisión de duplicados mantienen el mismo comportamiento; estas reglas no eliminan ni fusionan originales.</p>
 <button disabled={busy}>{busy?'Guardando…':'Guardar configuración avanzada'}</button></form>}
 </section></>;
}
