import { useEffect, useState } from 'react';
import { api, message } from './api';
import { Notice, PageEnd, usePage } from './components';
import { DocumentList, DocumentViewer } from './Documents';
import type { Library, Document } from './libraryTypes';
import type { CaseRecord, Requirements, Template } from './organizationTypes';

export function Cases({ library }: { library: Library }) {
  const [query, setQuery] = useState(''); const cases = usePage<CaseRecord>(`/libraries/${library.id}/cases?q=${encodeURIComponent(query)}`);
  const templates = usePage<Template>(`/libraries/${library.id}/templates`); const [selected, setSelected] = useState<CaseRecord | null>(null); const [creating, setCreating] = useState(false);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const canManage = library.permissions.includes('cases.manage');
  if (selected) return <CaseDetail library={library} initial={selected} back={() => { setSelected(null); cases.reload(); }} templates={templates.items} />;
  return <section className="card"><div className="section-heading"><div><h2>Expedientes</h2><p className="muted">Organiza documentos por {library.settings.identifier_label.toLowerCase()} y consulta sus requisitos.</p></div>{canManage && <button onClick={() => setCreating(!creating)}>Nuevo expediente</button>}</div><Notice text={error || cases.error || templates.error} />
    {creating && <form className="form-grid inset-form" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { const result = await api<{ id: string }>(`/libraries/${library.id}/cases`, { method: 'POST', body: { identifier: data.get('identifier'), exercise: data.get('exercise') || '', template_version_id: data.get('template') } }); setCreating(false); cases.reload(); setSelected(await api<CaseRecord>(`/cases/${result.id}`)); } catch (error) { setError(message(error)); } finally { setBusy(false); } }}><label>Identificador del expediente ({library.settings.identifier_label})<input name="identifier" required maxLength={160} autoFocus /></label>{library.settings.exercise_enabled && <label>Ejercicio<input name="exercise" required maxLength={40} /></label>}<label>Plantilla inicial<select name="template"><option value="">Sin plantilla (se puede inicializar después)</option>{templates.items.map(template => <option key={template.id} value={template.versions[0]?.id}>{template.name} · versión {template.versions[0]?.revision}</option>)}</select></label><div className="actions"><button disabled={busy}>Crear expediente</button><button type="button" className="secondary" onClick={() => setCreating(false)}>Cancelar</button></div></form>}
    <form className="filters" onSubmit={event => { event.preventDefault(); setQuery(String(new FormData(event.currentTarget).get('query') || '')); }}><label>Buscar identificador de expediente<input name="query" maxLength={160} /></label><button className="secondary">Filtrar expedientes</button></form>
    <div className="case-grid">{cases.items.map(item => <button className="case-card" key={item.id} onClick={() => setSelected(item)}><strong>{item.identifier}</strong><small>{item.exercise ? `Ejercicio ${item.exercise} · ` : ''}{item.requirements_initialized ? 'Requisitos inicializados' : 'Sin plantilla'}</small><span>Abrir expediente →</span></button>)}</div><PageEnd {...cases} empty={cases.items.length === 0} />
  </section>;
}
function CaseDetail({ library, initial, back, templates }: { library: Library; initial: CaseRecord; back: () => void; templates: Template[] }) {
  const [record, setRecord] = useState(initial); const [requirements, setRequirements] = useState<Requirements | null>(null); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const [revision, setRevision] = useState(0); const [selected, setSelected] = useState<Document | null>(null); const [associating, setAssociating] = useState(false);
  const documents = usePage<Document>(`/libraries/${library.id}/explorer?case_id=${record.id}`);
  const available = usePage<Document>(`/libraries/${library.id}/explorer?unassigned=true&storage_source=linked`);
  useEffect(() => { const controller = new AbortController(); void Promise.all([api<CaseRecord>(`/cases/${record.id}`, { signal: controller.signal }), api<Requirements>(`/cases/${record.id}/requirements`, { signal: controller.signal })]).then(([item, result]) => { setRecord(item); setRequirements(result); }).catch(error => { if (!controller.signal.aborted) setError(message(error)); }); return () => controller.abort(); }, [record.id, revision]);
  function reload() { setRevision(value => value + 1); documents.reload(); available.reload(); }
  return <><button className="text-button" onClick={back}>← Expedientes</button><section className="card"><div className="section-heading"><div><p className="eyebrow">{library.settings.identifier_label}</p><h2>{record.identifier}</h2>{record.exercise && <p>Ejercicio {record.exercise}</p>}</div><button className="secondary" onClick={reload}>Actualizar expediente</button></div><Notice text={error} /><Notice text={success} kind="success" />
    {library.permissions.includes('cases.manage') && <details><summary>Editar identificador</summary><form className="filters" key={record.revision} onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api(`/cases/${record.id}`, { method: 'PATCH', revision: record.revision, body: { identifier: data.get('identifier'), exercise: data.get('exercise') || '' } }); reload(); setSuccess('Expediente actualizado.'); } catch (error) { setError(message(error)); } }}><label>Identificador<input name="identifier" defaultValue={record.identifier} maxLength={160} required /></label>{library.settings.exercise_enabled && <label>Ejercicio del expediente<input name="exercise" defaultValue={record.exercise} required maxLength={40} /></label>}<button>Guardar expediente</button></form></details>}
    <div className="case-progress"><h3>Avance de requisitos obligatorios</h3>{requirements ? requirements.progress_percent === null ? <p>Sin requisitos obligatorios</p> : <><strong>{requirements.progress_percent.toFixed(0)} %</strong><progress value={requirements.progress_percent} max={100} aria-label="Avance del expediente" /><p className="muted">Se calcula con documentos aprobados válidos. La disponibilidad del original se muestra por separado.</p></> : <p role="status">Cargando requisitos…</p>}</div>
    {requirements && !requirements.initialized && library.permissions.includes('requirements.edit') && <form className="filters" onSubmit={async event => { event.preventDefault(); setBusy(true); try { await api(`/cases/${record.id}/initialize-requirements`, { method: 'POST', body: { template_version_id: new FormData(event.currentTarget).get('template') } }); reload(); setSuccess('Requerimientos inicializados.'); } catch (error) { setError(message(error)); } finally { setBusy(false); } }}><label>Plantilla para inicializar<select name="template" required><option value="">Selecciona una versión</option>{templates.flatMap(template => template.versions.map(version => <option key={version.id} value={version.id}>{template.name} · versión {version.revision}</option>))}</select></label><button disabled={busy}>Inicializar requerimientos</button></form>}
    <div className="requirements-list">{requirements?.items.map(item => <article className="requirement-card" key={item.id}><div className="section-heading"><div><h3>{item.category_name} · {item.document_type_name}</h3><p>{item.mandatory ? 'Obligatorio' : 'Opcional'} · Cantidad requerida: {item.required_count}</p></div><span className="badge">{item.counts.valid_approved || 0} aprobados válidos</span></div><p className="muted">{item.counts.draft || 0} borradores · {item.counts.pending_review || 0} en revisión · {item.available_count} originales disponibles · {item.missing_count} no disponibles</p>{library.permissions.includes('requirements.edit') && <details><summary>Ajustar requisito de este expediente</summary><form key={item.revision} className="filters" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api(`/cases/${record.id}/requirements/${item.id}`, { method: 'PATCH', revision: item.revision, body: { required_count: Number(data.get('count')), mandatory: data.get('mandatory') === 'on' } }); reload(); setSuccess('Requisito actualizado solo en este expediente.'); } catch (error) { setError(message(error)); } }}><label>Cantidad requerida<input name="count" type="number" min={1} max={item.allows_multiple ? 1000 : 1} defaultValue={item.required_count} required /></label><label className="check"><input name="mandatory" type="checkbox" defaultChecked={item.mandatory} />Obligatorio</label><button>Guardar requisito</button></form></details>}</article>)}</div>
  </section><section className="card"><div className="section-heading"><h2>Archivos del expediente</h2>{library.mode === 'hybrid' && library.permissions.includes('documents.associate') && <button className="secondary" onClick={() => setAssociating(!associating)}>Asociar archivo existente</button>}</div><Notice text={documents.error} /><DocumentList documents={documents.items} open={setSelected} /><PageEnd {...documents} empty={documents.items.length === 0} /></section>
    {associating && <section className="card"><h2>Archivos vinculados sin expediente</h2><p>Selecciona un archivo para clasificarlo y asociarlo. Conserva su ubicación y su texto extraído.</p><Notice text={available.error} /><DocumentList documents={available.items} open={setSelected} /><PageEnd {...available} empty={available.items.length === 0} /></section>}
    {selected && <DocumentViewer document={selected} preferredCaseID={!selected.case_id ? record.id : undefined} canRemove={library.permissions.includes('documents.remove_index')} close={() => setSelected(null)} changed={reload} />}
  </>;
}
