import { useState } from 'react';
import { api, message } from './api';
import { Notice, usePage } from './components';
import type { Library } from './libraryTypes';
import type { CatalogEntry, RequirementInput, Template } from './organizationTypes';

export function Catalogs({ library }: { library: Library }) {
  const categories = usePage<CatalogEntry>(`/libraries/${library.id}/categories`); const types = usePage<CatalogEntry>(`/libraries/${library.id}/document-types`);
  const [category, setCategory] = useState<CatalogEntry | null>(null); const [type, setType] = useState<CatalogEntry | null>(null);
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const canEdit = library.permissions.includes('catalogs.manage');
  async function save(kind: string, selected: CatalogEntry | null, data: FormData) {
    setBusy(true); setError('');
    try { await api(selected ? `/${kind}/${selected.id}` : `/libraries/${library.id}/${kind}`, { method: selected ? 'PATCH' : 'POST', revision: selected?.revision, body: { name: data.get('name'), category_id: data.get('category_id') || '', allows_multiple: data.get('multiple') === 'on', requires_descriptive_title: data.get('title_required') === 'on', archived: data.get('archived') === 'on' } }); categories.reload(); types.reload(); setCategory(null); setType(null); setSuccess('Catálogo guardado.'); } catch (error) { setError(message(error)); } finally { setBusy(false); }
  }
  return <><Notice text={error || categories.error || types.error} /><Notice text={success} kind="success" /><div className="editor-grid">
    <section className="card"><h2>Categorías</h2><div className="catalog-list">{categories.items.map(item => <div className="member-row" key={item.id}><strong>{item.name}</strong>{item.archived && <span className="badge">Archivada</span>}{canEdit && <button className="text-button" onClick={() => setCategory(item)}>Editar categoría {item.name}</button>}</div>)}</div>
      {canEdit && <form key={category?.id || 'new-category'} className="form-grid" onSubmit={event => { event.preventDefault(); void save('categories', category, new FormData(event.currentTarget)); }}><h3>{category ? 'Editar categoría' : 'Nueva categoría'}</h3><label>Nombre de categoría<input name="name" defaultValue={category?.name || ''} required maxLength={160} /></label>{category && <label className="check"><input name="archived" type="checkbox" defaultChecked={category.archived} />Archivar categoría</label>}<button disabled={busy}>{category ? 'Guardar categoría' : 'Crear categoría'}</button>{category && <button type="button" className="secondary" onClick={() => setCategory(null)}>Cancelar edición</button>}</form>}
    </section>
    <section className="card"><h2>Tipos de documento</h2><div className="catalog-list">{types.items.map(item => <div className="member-row" key={item.id}><strong>{item.name}</strong><small>{categories.items.find(category => category.id === item.category_id)?.name} · {item.allows_multiple ? 'Múltiples archivos' : 'Archivo único'}{item.requires_descriptive_title ? ' · Título obligatorio' : ''}</small>{item.archived && <span className="badge">Archivado</span>}{canEdit && <button className="text-button" onClick={() => setType(item)}>Editar tipo {item.name}</button>}</div>)}</div>
      {canEdit && <form key={type?.id || 'new-type'} className="form-grid" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); if (type) data.set('category_id', type.category_id); void save('document-types', type, data); }}><h3>{type ? 'Editar tipo' : 'Nuevo tipo'}</h3><label>Categoría del tipo<select name="category_id" defaultValue={type?.category_id || ''} disabled={!!type} required><option value="">Selecciona una categoría</option>{categories.items.filter(category => !category.archived || category.id === type?.category_id).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Nombre del tipo<input name="name" defaultValue={type?.name || ''} required maxLength={160} /></label><label className="check"><input type="checkbox" name="multiple" defaultChecked={type?.allows_multiple} />Admite múltiples archivos</label><label className="check"><input type="checkbox" name="title_required" defaultChecked={type?.requires_descriptive_title} />Exige título descriptivo (por ejemplo, Varios)</label>{type && <label className="check"><input name="archived" type="checkbox" defaultChecked={type.archived} />Archivar tipo</label>}<button disabled={busy}>{type ? 'Guardar tipo' : 'Crear tipo'}</button>{type && <button type="button" className="secondary" onClick={() => setType(null)}>Cancelar edición</button>}</form>}
    </section></div>
    {library.settings.cases_enabled && <Templates library={library} categories={categories.items} types={types.items} />}
  </>;
}
function Templates({ library, categories, types }: { library: Library; categories: CatalogEntry[]; types: CatalogEntry[] }) {
  const templates = usePage<Template>(`/libraries/${library.id}/templates`); const [selected, setSelected] = useState<Template | null>(null);
  const [requirements, setRequirements] = useState<RequirementInput[]>([]); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const canEdit = library.permissions.includes('templates.manage');
  return <section className="card"><h2>Plantillas de expedientes</h2><p className="muted">Cada expediente conserva sus propios requisitos. Una nueva versión solo se aplica a expedientes nuevos.</p><Notice text={error || templates.error} /><Notice text={success} kind="success" />
    <div className="catalog-list">{templates.items.map(template => <details key={template.id}><summary>{template.name} · versión {template.versions[0]?.revision}</summary>{template.versions.map(version => <p key={version.id}>Versión {version.revision}: {version.requirements.map(requirement => `${types.find(type => type.id === requirement.document_type_id)?.name || 'Tipo'} (${requirement.required_count}${requirement.mandatory ? ', obligatorio' : ', opcional'})`).join('; ') || 'Sin requerimientos'}</p>)}{canEdit && <button className="secondary" onClick={() => { setSelected(template); setRequirements(template.versions[0]?.requirements.map(item => ({ category_id: item.category_id, document_type_id: item.document_type_id, required_count: item.required_count, mandatory: item.mandatory })) || []); }}>Crear nueva versión de {template.name}</button>}</details>)}</div>
    {canEdit && <form key={selected?.id || 'new-template'} className="form-grid" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api(selected ? `/templates/${selected.id}/versions` : `/libraries/${library.id}/templates`, { method: 'POST', revision: selected?.versions[0]?.revision, body: { name: data.get('name') || selected?.name, requirements } }); templates.reload(); setSelected(null); setRequirements([]); setSuccess('Versión de plantilla creada.'); } catch (error) { setError(message(error)); } finally { setBusy(false); } }}><h3>{selected ? `Nueva versión de ${selected.name}` : 'Nueva plantilla'}</h3>{!selected && <label>Nombre de plantilla<input name="name" required maxLength={160} /></label>}
      {types.filter(type => !type.archived && !categories.find(category => category.id === type.category_id)?.archived).map(type => { const requirement = requirements.find(item => item.document_type_id === type.id); return <div className="requirement-editor" key={type.id}><label className="check"><input type="checkbox" checked={!!requirement} onChange={event => setRequirements(event.target.checked ? [...requirements, { category_id: type.category_id, document_type_id: type.id, required_count: 1, mandatory: true }] : requirements.filter(item => item.document_type_id !== type.id))} />Incluir {type.name}</label>{requirement && <><label>Cantidad de {type.name}<input type="number" min={1} max={type.allows_multiple ? 1000 : 1} value={requirement.required_count} required onChange={event => setRequirements(requirements.map(item => item.document_type_id === type.id ? { ...item, required_count: Number(event.target.value) } : item))} /></label><label className="check"><input type="checkbox" checked={requirement.mandatory} onChange={event => setRequirements(requirements.map(item => item.document_type_id === type.id ? { ...item, mandatory: event.target.checked } : item))} />{type.name} obligatorio</label></>}</div>; })}
      <button disabled={busy}>{selected ? 'Guardar nueva versión' : 'Crear plantilla'}</button>{selected && <button type="button" className="secondary" onClick={() => { setSelected(null); setRequirements([]); }}>Cancelar versión</button>}
    </form>}
  </section>;
}
