import { formatDate } from './api';
import { Notice, usePolling } from './components';
import { CursorControls, useCursorPage } from './CursorPage';
import { formatSize } from './ExplorerEntries';
import { processingStateLabel } from './libraryTypes';
import { approvalLabel } from './organizationTypes';
import { moduleLabels, type DiagnosticEvent } from './SystemErrors';
import { DashboardChart, type ChartValue } from './DashboardChart';

interface Group { key: string; count: number }
interface Report { generated_at:string;timezone:string;today:number;week:number;month:number;total:number;indexed:number;ocr:number;linked:number;managed:number;duplicate_groups:number;duplicate_files:number;extra_copies:number;queue:Group[];formats:Group[];states:Group[];approval:Group[];cache_bytes:number;cache_limit_mb:number;cache_entries:number;average_seconds:number|null;timing_samples:number;paused:boolean;recent_errors:DiagnosticEvent[];daily:{date:string;count:number}[] }
interface LibraryMetric { id:string;name:string;mode:string;total:number;indexed:number;errors:number }
const number = (value:number) => value.toLocaleString('es-MX');
const colors:Record<string,string> = { pdf:'#d06b55',docx:'#356daf',xlsx:'#278768',txt:'#7c6caa',csv:'#c39234',unknown:'#71838c',completed:'#007d6e',completed_with_warnings:'#b77922',pending:'#3a78b1',processing:'#4d69a7',error:'#c45252',paused:'#8b6da8',stored_only:'#71838c',cancelled:'#958c80' };
const stateLabels = {...processingStateLabel,processing:'En proceso',stored_only:'Conservado sin indexación'};
const queueLabels:Record<string,string> = {queued:'En cola',retry_wait:'Esperando reintento',paused:'Pausados',running:'En ejecución',preview_queued:'Vistas previas en cola',preview_generating:'Vistas previas en generación'};
function values(groups:Group[],labels?:Record<string,string>):ChartValue[] {return groups.map(group=>({label:labels?.[group.key]||group.key.toUpperCase(),count:group.count,color:colors[group.key]||'#71838c'}))}
function DataTable({ title, entries }: {title:string;entries:ChartValue[]}) {
  return <details className="chart-data"><summary>Ver datos de {title.toLocaleLowerCase('es-MX')}</summary><div className="table-wrap"><table aria-label={title}><thead><tr><th>Grupo</th><th>Cantidad</th></tr></thead><tbody>{entries.map(entry=><tr key={entry.label}><td>{entry.label}</td><td>{number(entry.count)}</td></tr>)}</tbody></table></div></details>;
}
function Distribution({title,subtitle,entries,total}:{title:string;subtitle:string;entries:ChartValue[];total:number}) {
  return <section className="card dashboard-card"><div className="section-heading"><div><h2>{title}</h2><p className="muted">{subtitle}</p></div></div>
    {total>0?<><div className="donut-layout"><div className="donut-container"><DashboardChart kind="doughnut" title={title} values={entries}/><div className="donut-total" aria-hidden="true"><strong>{number(total)}</strong><span>documentos</span></div></div><ul className="chart-legend">{entries.map(entry=><li key={entry.label}><span className="legend-dot" style={{backgroundColor:entry.color}}/><span>{entry.label}</span><strong>{number(entry.count)}</strong><small>{(entry.count*100/total).toLocaleString('es-MX',{maximumFractionDigits:1})}%</small></li>)}</ul></div><DataTable title={title} entries={entries}/></>:<p className="chart-empty">Aún no hay documentos para esta gráfica.</p>}
  </section>;
}
function Metric({label,value,note,tone,icon}:{label:string;value:number;note:string;tone:string;icon:'files'|'check'|'plus'|'queue'}) {
  const paths={files:'M7 3h7l4 4v14H7z M14 3v5h5 M4 7v17h11',check:'M7 12l4 4 8-10 M4 3h16v19H4z',plus:'M12 4v16 M4 12h16',queue:'M5 5h15 M5 12h15 M5 19h15 M2 5h.1 M2 12h.1 M2 19h.1'};
  return <article className={`metric dashboard-metric metric-${tone}`}><div><span>{label}</span><strong>{number(value)}</strong><small>{note}</small></div><svg className="metric-symbol" width="44" height="44" viewBox="0 0 26 26" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[icon]}/></svg></article>;
}
export function Dashboard() {
  const report=usePolling<Report>('/system/dashboard',15000);
  const libraries=useCursorPage<LibraryMetric>('/system/dashboard/libraries');const data=report.data;
  const queue=data?.queue.reduce((sum,item)=>sum+item.count,0)||0;
  const stateErrors=data?.states.find(item=>item.key==='error')?.count||0;
  const daily=(data?.daily||[]).map(item=>({label:new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'}).format(new Date(`${item.date}T12:00:00`)),count:item.count,color:'#007d6e'}));
  const cachePercent=data?Math.min(100,data.cache_bytes/(data.cache_limit_mb*1048576)*100):0;
  return <div className="dashboard"><header className="page-heading dashboard-heading"><div><p className="eyebrow">VISTA DE LA INSTALACIÓN</p><h1>Dashboard</h1><p>Tu biblioteca digital, en perspectiva.</p></div><div className="dashboard-refresh"><button className="secondary" onClick={()=>{report.reload();libraries.reload()}}>Actualizar Dashboard</button>{data&&<small>Actualizado: {formatDate(data.generated_at)}</small>}</div></header>
    <Notice text={report.error||libraries.error}/>{!data&&!report.error&&<p role="status">Consultando indicadores…</p>}
    {data&&<>
      <div className="dashboard-kpis"><Metric label="Total de documentos" value={data.total} note={`${number(data.linked)} vinculados · ${number(data.managed)} administrados`} tone="navy" icon="files"/><Metric label="Con índice vigente" value={data.indexed} note={`${number(data.ocr)} procesados con OCR`} tone="teal" icon="check"/><Metric label="Incorporados hoy" value={data.today} note={`${number(data.week)} esta semana · ${number(data.month)} este mes`} tone="blue" icon="plus"/><Metric label="Trabajos activos y en espera" value={queue} note={data.paused?'Procesamiento pausado':`${number(stateErrors)} documentos con error`} tone="slate" icon="queue"/></div>
      <div className="dashboard-chart-grid">
        <section className="card dashboard-card"><div className="section-heading"><div><h2>Incorporaciones diarias</h2><p className="muted">Últimos 30 días · hora del servidor ({data.timezone})</p></div><span className="badge">{number(daily.reduce((sum,item)=>sum+item.count,0))} documentos</span></div><DashboardChart kind="line" title="Incorporaciones diarias" values={daily}/><div className="trend-summary"><span>Hoy <strong>{number(data.today)}</strong></span><span>Esta semana <strong>{number(data.week)}</strong></span><span>Este mes <strong>{number(data.month)}</strong></span></div><DataTable title="Incorporaciones diarias" entries={daily}/></section>
        <Distribution title="Documentos por formato" subtitle="Distribución del contenido registrado" entries={values(data.formats)} total={data.total}/>
        <section className="card dashboard-card"><div className="section-heading"><div><h2>Estado de procesamiento</h2><p className="muted">Situación actual de los documentos</p></div><span className={`badge ${stateErrors?'dashboard-error-badge':''}`}>{number(stateErrors)} con error</span></div>{data.total>0?<><DashboardChart kind="bar" title="Estado de procesamiento" values={values(data.states,stateLabels)}/><DataTable title="Estado de procesamiento" entries={values(data.states,stateLabels)}/></>:<p className="chart-empty">Aún no hay documentos para esta gráfica.</p>}</section>
        <Distribution title="Origen de los documentos" subtitle="Las bibliotecas híbridas pueden aportar a ambos" entries={[{label:'Vinculados',count:data.linked,color:'#007d6e'},{label:'Administrados',count:data.managed,color:'#416a99'}]} total={data.total}/>
      </div>
      <div className="dashboard-summary-grid">
        <section className="card dashboard-card"><h2>Contenido duplicado</h2><strong className="dashboard-big-number">{number(data.duplicate_groups)} <small>grupos detectados</small></strong><p>{number(data.duplicate_files)} documentos · {number(data.extra_copies)} copias adicionales</p><p className="muted">Se comparan los contenidos actuales. Cada archivo conserva su registro y ubicación.</p></section>
        <section className="card dashboard-card"><h2>Caché de vistas previas</h2><strong className="dashboard-big-number">{formatSize(data.cache_bytes)}</strong><div className="cache-meter" role="meter" aria-label="Uso de caché" aria-valuemin={0} aria-valuemax={100} aria-valuenow={cachePercent} aria-valuetext={`${formatSize(data.cache_bytes)} de ${formatSize(data.cache_limit_mb*1048576)}`}><span style={{width:`${cachePercent}%`}}/></div><p>{formatSize(data.cache_limit_mb*1048576)} de capacidad · {number(data.cache_entries)} vistas disponibles</p><a href="/admin/previews">Administrar caché</a></section>
        <section className="card dashboard-card"><h2>Tiempo de procesamiento</h2>{data.average_seconds===null?<p className="muted">Aún no hay mediciones suficientes.</p>:<><strong className="dashboard-big-number">{data.average_seconds.toLocaleString('es-MX',{maximumFractionDigits:1})} <small>segundos de promedio</small></strong><p>{number(data.timing_samples)} extracciones terminadas en 24 horas</p></>}<p className="muted">Intentos finales exitosos. Incluye lectura, espera de OCR y publicación; excluye la espera inicial en cola.</p></section>
      </div>
      <div className="dashboard-grid">
        <section className="card dashboard-card"><div className="section-heading"><h2>Actividad del procesamiento</h2><span className="badge">{data.paused?'Pausado':'Habilitado'}</span></div>{data.queue.length?<ul className="dashboard-count-list">{data.queue.map(item=><li key={item.key}><span>{queueLabels[item.key]||item.key}</span><strong>{number(item.count)}</strong></li>)}</ul>:<p className="dashboard-quiet">No hay trabajos en curso ni en espera.</p>}<p className="muted">Las tareas pueden esperar por reglas, licencia o recursos.</p><h3>Estado documental</h3><ul className="document-state-list">{data.approval.map(item=><li key={item.key}>{approvalLabel[item.key]||item.key} <strong>{number(item.count)}</strong></li>)}</ul></section>
        <section className="card dashboard-card"><div className="section-heading"><h2>Errores recientes</h2><a href="/admin/errors">Ver diagnósticos</a></div>{!data.recent_errors.length?<p className="dashboard-quiet">No hay errores recientes registrados.</p>:<ul className="dashboard-errors">{data.recent_errors.map(event=><li key={event.id}><span className="diagnostic-dot"/><div><strong>{event.message}</strong><small>{formatDate(event.last_occurred_at)} · {moduleLabels[event.module]} · {event.code}</small></div></li>)}</ul>}<a href="/admin/errors">Consultar errores del sistema</a></section>
      </div>
    </>}
    <section className="card"><div className="section-heading"><h2>Documentos por biblioteca</h2><button className="secondary" disabled={libraries.busy} onClick={libraries.reload}>Actualizar bibliotecas del Dashboard</button></div><div className="table-wrap"><table aria-label="Documentos por biblioteca"><thead><tr><th>Biblioteca</th><th>Modalidad</th><th>Documentos</th><th>Índice vigente</th><th>Con error</th></tr></thead><tbody>{libraries.items.map(library=><tr key={library.id}><td>{library.name}</td><td>{{linked:'Vinculada',managed:'Administrada',hybrid:'Híbrida'}[library.mode]||library.mode}</td><td>{number(library.total)}</td><td>{number(library.indexed)}</td><td>{number(library.errors)}</td></tr>)}</tbody></table></div>{!libraries.busy&&!libraries.items.length&&<p className="empty-state">Todavía no hay bibliotecas activas.</p>}<CursorControls page={libraries} label="Bibliotecas del Dashboard"/></section>
    <details className="dashboard-definitions"><summary>Cómo se calculan los indicadores</summary><p>Documentos no retirados de bibliotecas activas, incluidos borradores privados. Los totales administrativos no conceden acceso a su contenido. Cada documento cuenta una vez, aunque tenga varias rutas.</p><p>Las incorporaciones usan la fecha de registro. Los reprocesamientos no son incorporaciones nuevas; retirar un documento lo excluye también de la tendencia. La semana comienza el lunes según la hora del servidor. Los indicadores se actualizan cada 15 segundos.</p><p>OCR cuenta los documentos con índice vigente que pasaron por reconocimiento, incluso cuando una página devolvió texto vacío. Los estados de procesamiento y de publicación documental son independientes.</p></details>
  </div>;
}
