import { useState, type FormEvent } from 'react';
import { api, formatDate, message } from './api';
import { Notice, PageEnd, usePage } from './components';
import { diagnosticLabel, jobLabel, type Library, type Root, type RootPlan, type Job } from './libraryTypes';

export function Roots({ library, refresh }: { library: Library; refresh: () => void }) {
  const roots = usePage<Root>(`/libraries/${library.id}/roots`);
  const [plan, setPlan] = useState<RootPlan | null>(null);
  const [retirement, setRetirement] = useState<{ plan_id: string; root_id: string; reference_count: number; affected_case_count: number } | null>(null);
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  async function operation(action: () => Promise<unknown>, text: string) { setBusy(true); setError(''); setSuccess(''); try { await action(); roots.reload(); refresh(); setSuccess(text); } catch (error) { setError(message(error)); } finally { setBusy(false); } }
  function inspect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void operation(async () => setPlan(await api<RootPlan>(`/libraries/${library.id}/root-plans`, { method: 'POST', body: { server_path: data.get('server_path'), storage_source: data.get('source') || 'linked' } })), 'Carpeta inspeccionada. Revisa el resultado antes de confirmar.'); }
  const parent = plan ? roots.items.find(root => root.id === plan.related_root_ids[0]) : undefined;
  const prefix = parent?.server_path && plan ? plan.server_path.replaceAll('\\', '/').slice(parent.server_path.replaceAll('\\', '/').length + 1) : '';
  return <><Notice text={error || roots.error} /><Notice text={success} kind="success" />
    <section className="card"><div className="section-heading"><div><h2>Carpetas de la biblioteca</h2><p className="muted">Las vinculadas se consultan sin mover originales. Las administradas guardan los documentos confirmados y verifican su integridad.</p></div><button className="secondary" onClick={roots.reload}>Actualizar raíces</button></div>
      {roots.items.length === 0 && <p className="empty-state">Añade la primera carpeta para comenzar a indexar.</p>}
      {roots.items.filter(root => root.status !== 'superseded').map(root => <div className="root-row" key={root.id}><strong className="path-text">{root.server_path || 'Carpeta vinculada'}</strong><div className="document-badges"><span className="badge">{root.storage_source === 'managed' ? 'Destino administrado' : 'Vinculada'}</span><span className={`badge ${root.status === 'active' ? 'positive' : ''}`}>{({ active: 'Activa', inaccessible: 'Sin acceso', disabled: 'Pausada', retired: 'Retirada' } as Record<string, string>)[root.status]}</span><span className="muted">{root.storage_source === 'managed' ? root.watch_mode === 'paused' ? 'Verificación pausada' : 'Verificación periódica' : root.watch_mode === 'native' ? 'Vigilancia nativa' : root.watch_mode === 'paused' ? 'Vigilancia pausada' : 'Reconciliación periódica'}</span></div><small>Última comprobación: {formatDate(root.last_scan_at || null)}</small>{root.last_error_code && <p className="diagnostic">{diagnosticLabel[root.last_error_code] || root.last_error_code}</p>}
        <details><summary>Configurar carpeta</summary><form className="filters" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void operation(() => api(`/roots/${root.id}`, { method: 'PATCH', revision: root.revision, body: { enabled: data.get('enabled') === 'on', reconcile_interval_seconds: Number(data.get('interval')) } }), 'Configuración de vigilancia guardada.'); }}><label className="check"><input type="checkbox" name="enabled" defaultChecked={root.status === 'active' || root.status === 'inaccessible'} />Verificación habilitada</label><label>Comprobar cada (segundos)<input type="number" name="interval" min={10} max={86400} defaultValue={root.reconcile_interval_seconds} required /></label><button disabled={busy}>Guardar verificación</button></form><button className="secondary" disabled={busy} onClick={() => void operation(async () => setRetirement(await api(`/roots/${root.id}/retirement-plans`, { method: 'POST' })), 'Revisa el alcance del retiro.')}>Preparar retiro</button></details>
      </div>)}
    </section>
    {retirement && <section className="card"><h2>Confirmar retiro de carpeta</h2><p>Afecta {retirement.reference_count} referencias. Los originales permanecen en disco.</p>{retirement.affected_case_count > 0 && <p className="notice error">Hay documentos asociados a {retirement.affected_case_count} expedientes. Retirar sus referencias del índice reduce sus conteos y puede cambiar su avance.</p>}<form className="form-grid" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void operation(async () => { await api(`/roots/${retirement.root_id}/retire`, { method: 'POST', body: { plan_id: retirement.plan_id, reference_policy: data.get('policy') } }); setRetirement(null); }, 'Carpeta retirada.'); }}><label>Referencias existentes<select name="policy"><option value="retain_index">Conservar texto y resultados de búsqueda</option><option value="remove_index_references">Retirar sus documentos del índice</option></select></label><div className="actions"><button disabled={busy}>Confirmar retiro</button><button className="secondary" type="button" onClick={() => setRetirement(null)}>Cancelar</button></div></form></section>}
    <section className="card"><h2>Añadir carpeta</h2><p className="muted">Introduce una ruta absoluta del equipo donde corre el servicio.</p><form className="filters" onSubmit={inspect}>{library.mode !== 'linked' && <label>Origen de la carpeta<select name="source" defaultValue={library.mode === 'managed' ? 'managed' : 'linked'}>{library.mode === 'hybrid' && <option value="linked">Vinculada: consultar originales</option>}<option value="managed">Administrada: guardar definitivos</option></select></label>}<label>Ruta de la carpeta en el servidor<input name="server_path" required placeholder="/ruta/a/documentos" /></label><button disabled={busy}>Inspeccionar carpeta</button></form>
      {plan && <div className="root-plan"><p className="path-text"><strong>{plan.server_path}</strong></p>
        {plan.relation === 'equal' ? <p>Esta carpeta ya está registrada. Puedes administrarla en la lista de raíces.</p> : plan.relation === 'descendant' ? <><p>Esta subcarpeta ya pertenece a una raíz. Puedes crear una vista para consultarla por separado.</p><form className="filters" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void operation(async () => { await api(`/libraries/${library.id}/folder-views`, { method: 'POST', body: { root_id: plan.related_root_ids[0], relative_prefix: prefix, name: data.get('name') } }); setPlan(null); }, 'Vista creada.'); }}><label>Nombre de la vista<input name="name" required maxLength={160} defaultValue={prefix} /></label><button disabled={busy}>Crear vista lógica</button></form></> : <><p>{plan.relation === 'ancestor' ? `Contiene ${plan.related_root_ids.length} raíces existentes. La consolidación conservará sus documentos, texto e historial.` : plan.storage_source === 'managed' ? 'Carpeta disponible como destino administrado.' : 'Carpeta disponible para registrar e indexar.'}</p>{plan.relation === 'ancestor' && <ul>{plan.related_root_ids.map(identifier => <li className="path-text" key={identifier}>{roots.items.find(root => root.id === identifier)?.server_path}</li>)}</ul>}<button disabled={busy} onClick={() => void operation(async () => { await api(`/libraries/${library.id}/${plan.relation === 'ancestor' ? 'root-consolidations' : 'roots'}`, { method: 'POST', body: { plan_id: plan.id, expected_configuration_revision: plan.expected_configuration_revision } }); setPlan(null); }, plan.storage_source === 'managed' ? 'Destino administrado registrado. Selecciónalo en Configuración.' : 'Raíz registrada. El escaneo está en cola.')}>{plan.relation === 'ancestor' ? 'Confirmar consolidación' : plan.storage_source === 'managed' ? 'Registrar destino administrado' : 'Registrar e indexar'}</button></>}
      </div>}
    </section>
  </>;
}

export function LibraryJobs({ library }: { library: Library }) {
  const jobs = usePage<Job>(`/libraries/${library.id}/jobs`); const [error, setError] = useState('');
  return <section className="card"><div className="section-heading"><div><h2>Procesamiento</h2><p className="muted">Cada tarea admite hasta cinco intentos. Puedes consultar el historial completo.</p></div><button className="secondary" onClick={jobs.reload}>Actualizar tareas</button></div><Notice text={error || jobs.error} /><div className="table-wrap"><table><thead><tr><th>Tarea</th><th>Estado</th><th>Intentos</th><th>Diagnóstico</th><th>Acciones</th></tr></thead><tbody>{jobs.items.map(job => <tr key={job.id}><td>{({ scan: 'Reconciliar carpeta', extract: 'Extraer texto y OCR', verify_managed: 'Verificar integridad', materialize: 'Guardar documento definitivo' } as Record<string, string>)[job.job_type] || job.job_type}<small>{formatDate(job.created_at)}</small></td><td>{jobLabel[job.status]}</td><td>{job.attempt_count} / 5</td><td>{diagnosticLabel[job.last_error_code] || job.last_error_code || '—'}</td><td>{['failed', 'cancelled'].includes(job.status) && <button className="text-button" onClick={async () => { const reason = window.prompt('Motivo del reintento'); if (!reason) return; try { await api(`/jobs/${job.id}/retry`, { method: 'POST', body: { reason } }); jobs.reload(); } catch (error) { setError(message(error)); } }}>Reintentar</button>}</td></tr>)}</tbody></table></div><PageEnd {...jobs} empty={jobs.items.length === 0} /></section>;
}

export function LibraryMembers({ library }: { library: Library }) {
  const members = usePage<{ user_id: string; display_name: string; role_ids: string[] }>(`/libraries/${library.id}/members`);
  const [filter, setFilter] = useState(''); const candidates = usePage<{ id: string; display_name: string; username: string }>(`/libraries/${library.id}/member-candidates?q=${encodeURIComponent(filter)}`);
  const [selected, setSelected] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const existing = members.items.find(member => member.user_id === selected);
  return <section className="card"><h2>Personas y permisos</h2><p className="muted">El acceso se concede por biblioteca. Puedes combinar perfiles.</p><Notice text={error || members.error || candidates.error} /><Notice text={success} kind="success" />
    <div className="editor-grid"><div>{members.items.map(member => <div className="member-row" key={member.user_id}><strong>{member.display_name}</strong><small>{member.role_ids.map(role => ({ library_reader: 'Lector', library_manager: 'Gestor', library_auditor: 'Auditor', library_contributor: 'Colaborador', library_reviewer: 'Revisor' }[role])).join(', ')}</small><button className="text-button" onClick={() => setSelected(member.user_id)}>Editar permisos</button></div>)}</div><div>
      <form className="filters" onSubmit={event => { event.preventDefault(); setFilter(String(new FormData(event.currentTarget).get('query') || '')); }}><label>Buscar persona<input name="query" maxLength={120} /></label><button className="secondary">Buscar persona</button></form>
      <label>Persona<select value={selected} onChange={event => setSelected(event.target.value)}><option value="">Selecciona una cuenta</option>{candidates.items.map(candidate => <option value={candidate.id} key={candidate.id}>{candidate.display_name} · {candidate.username}</option>)}</select></label>
      {selected && <form key={selected + ':' + existing?.role_ids.join(',')} className="form-grid member-editor" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api(`/libraries/${library.id}/members/${selected}`, { method: 'PUT', body: { role_ids: data.getAll('roles') } }); setSuccess('Permisos guardados.'); setError(''); members.reload(); } catch (error) { setError(message(error)); } }}>
        <label className="check"><input name="roles" type="checkbox" value="library_reader" defaultChecked={existing?.role_ids.includes('library_reader')} />Lector: consulta y descarga</label><label className="check"><input name="roles" type="checkbox" value="library_manager" defaultChecked={existing?.role_ids.includes('library_manager')} />Gestor: documentos, raíces y personas</label><label className="check"><input name="roles" type="checkbox" value="library_auditor" defaultChecked={existing?.role_ids.includes('library_auditor')} />Auditor: eventos y consultas exactas</label><label className="check"><input name="roles" type="checkbox" value="library_contributor" defaultChecked={existing?.role_ids.includes('library_contributor')} />Colaborador: cargar y clasificar</label><label className="check"><input name="roles" type="checkbox" value="library_reviewer" defaultChecked={existing?.role_ids.includes('library_reviewer')} />Revisor: consultar, aprobar y rechazar</label><button>Guardar permisos de biblioteca</button>
      </form>}
    </div></div>
  </section>;
}
