import { useState } from 'react';
import { api, message } from './api';
import { Notice, usePage } from './components';
import type { Library, Root } from './libraryTypes';
import { modeLabel } from './organizationTypes';

export function ManagedSettings({ library, refresh }: { library: Library; refresh: () => void }) {
  const [settings, setSettings] = useState(library.settings); const [mode, setMode] = useState(library.mode);
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [preview, setPreview] = useState(''); const [busy, setBusy] = useState(false);
  const roots = usePage<Root>(`/libraries/${library.id}/roots`);
  return <section className="card"><h2>Configuración de biblioteca</h2><Notice text={error || roots.error} /><Notice text={success} kind="success" />
    <form className="form-grid" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api(`/libraries/${library.id}`, { method: 'PATCH', revision: library.revision, body: { name: data.get('name'), ocr_languages: data.get('languages'), mode, settings } }); refresh(); setSuccess('Configuración guardada.'); } catch (error) { setError(message(error)); } finally { setBusy(false); } }}>
      <div className="editor-grid"><label>Nombre de la biblioteca<input name="name" defaultValue={library.name} maxLength={160} required /></label><label>Idioma del OCR<select name="languages" defaultValue={library.ocr_languages}><option value="spa">Español</option><option value="eng">Inglés</option><option value="spa+eng">Español e inglés</option></select></label></div>
      <label>Modalidad<select value={mode} onChange={event => setMode(event.target.value)}><option value={library.mode}>{modeLabel[library.mode]}</option>{library.mode !== 'hybrid' && <option value="hybrid">Híbrida</option>}</select></label>
      {mode !== library.mode && <p className="notice success">La ampliación conserva archivos, texto extraído, permisos e historial.</p>}
      {mode !== 'linked' && <><div className="editor-grid"><label className="check"><input type="checkbox" checked={settings.cases_enabled} onChange={event => setSettings({ ...settings, cases_enabled: event.target.checked, structure_pattern: event.target.checked ? '{identificador}/{categoria}' : '{categoria}', filename_pattern: 'original' })} />Utilizar expedientes</label><label>Etiqueta del identificador<input value={settings.identifier_label} maxLength={60} required onChange={event => setSettings({ ...settings, identifier_label: event.target.value })} /></label><label className="check"><input type="checkbox" checked={settings.exercise_enabled} onChange={event => setSettings({ ...settings, exercise_enabled: event.target.checked, structure_pattern: settings.cases_enabled ? '{identificador}/{categoria}' : '{categoria}', filename_pattern: 'original' })} />Utilizar ejercicio</label></div>
        <h3>Destino para incorporaciones futuras</h3><label>Carpeta administrada<select value={settings.default_managed_root_id} onChange={event => setSettings({ ...settings, default_managed_root_id: event.target.value })}><option value="">Sin seleccionar</option>{roots.items.filter(root => root.storage_source === 'managed' && root.status === 'active').map(root => <option key={root.id} value={root.id}>{root.server_path || root.id}</option>)}</select></label><p className="muted">Registra los destinos en Carpetas. Las cargas permanecen privadas hasta su incorporación definitiva.</p>
        <div className="editor-grid"><label>Estructura de carpetas<select value={settings.structure_pattern} onChange={event => setSettings({ ...settings, structure_pattern: event.target.value })}><option value="{categoria}">Categoría</option>{settings.cases_enabled && <><option value="{identificador}/{categoria}">Identificador / Categoría</option><option value="{categoria}/{identificador}">Categoría / Identificador</option><option value="{identificador}">Identificador</option>{settings.exercise_enabled && <option value="{ejercicio}/{identificador}/{categoria}">Ejercicio / Identificador / Categoría</option>}</>}</select></label>
          <label>Nombre de archivo<select value={settings.filename_pattern} onChange={event => setSettings({ ...settings, filename_pattern: event.target.value })}><option value="original">Conservar nombre original</option><option value="{tipo_documento}_{consecutivo}">Tipo y consecutivo</option>{settings.cases_enabled && <option value="{prefijo}_{identificador}_{tipo_documento}_{consecutivo}">Prefijo, identificador, tipo y consecutivo</option>}{settings.exercise_enabled && <option value="{ejercicio}_{tipo_documento}_{consecutivo}">Ejercicio, tipo y consecutivo</option>}</select></label><label>Prefijo<input value={settings.filename_prefix} maxLength={40} onChange={event => setSettings({ ...settings, filename_prefix: event.target.value })} /></label></div>
        <p className="muted">Los cambios afectan archivos futuros. Se añade un identificador estable para evitar colisiones.</p>
      </>}
      {mode !== 'linked' && <fieldset><legend>Revisión y conservación</legend><label className="check"><input type="checkbox" checked={settings.review_managed} onChange={event => setSettings({ ...settings, review_managed: event.target.checked })} />Exigir revisión para documentos administrados</label>{mode === 'hybrid' && <label className="check"><input type="checkbox" checked={settings.review_linked} onChange={event => setSettings({ ...settings, review_linked: event.target.checked })} />Exigir revisión inicial para asociaciones vinculadas</label>}<p className="muted">Sin revisión, un gestor confirma el documento. Con revisión, otra persona con perfil Revisor toma la decisión.</p><label>Conservar temporales rechazados o cancelados (días)<input type="number" min={0} max={3650} value={settings.retention_days} onChange={event => setSettings({ ...settings, retention_days: Number(event.target.value) })} required /></label><p className="muted">0 conserva los temporales. Otro valor programa su eliminación desde el siguiente rechazo o cancelación; el texto y el historial se conservan privados.</p></fieldset>}
      <button disabled={busy}>Guardar configuración</button>
    </form>
    {mode !== 'linked' && <details className="naming-preview"><summary>Vista previa del formato guardado</summary><form className="filters" onSubmit={async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api<{ relative_path: string }>(`/libraries/${library.id}/naming-preview`, { method: 'POST', body: values }); setPreview(result.relative_path); setError(''); } catch (error) { setError(message(error)); } }}><label>Identificador de ejemplo<input name="identifier" defaultValue="PR-008" /></label><label>Ejercicio de ejemplo<input name="exercise" defaultValue="2026" /></label><label>Categoría de ejemplo<input name="category" defaultValue="Planos" /></label><label>Tipo de ejemplo<input name="document_type" defaultValue="Plano general" /></label><input type="hidden" name="original_filename" value="Plano.pdf" /><button className="secondary">Ver ejemplo</button></form>{preview && <p className="path-text naming-result">{preview}</p>}</details>}
  </section>;
}
