import { useEffect, useState } from 'react';
import { api, message } from './api';
import { Notice } from './components';
interface Settings { enabled:boolean;maximum_cache_mb:number;maximum_idle_days:number;maximum_source_mb:number;automatic_cleanup:boolean;converter_path:string;revision:number;used_bytes:number;entries:number;converter_available:boolean }
export function PreviewSettings(){
 const [settings,setSettings]=useState<Settings|null>(null);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);
 async function load(){setSettings(await api<Settings>('/system/previews'));}
 useEffect(()=>{void load().catch(cause=>setError(message(cause)));},[]);
 async function save(){if(!settings)return;setBusy(true);setError('');setSuccess('');try{setSettings(await api<Settings>('/system/previews',{method:'PUT',body:{enabled:settings.enabled,maximum_cache_mb:settings.maximum_cache_mb,maximum_idle_days:settings.maximum_idle_days,maximum_source_mb:settings.maximum_source_mb,automatic_cleanup:settings.automatic_cleanup,converter_path:settings.converter_path,revision:settings.revision}}));setSuccess('Configuración de vistas previas guardada.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function clear(){setBusy(true);setError('');setSuccess('');try{await api('/system/previews/clear',{method:'POST',body:{confirm:true}});await load();setConfirm(false);setSuccess('Caché vaciada. Las vistas se generarán de nuevo cuando se soliciten.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 return <><header className="page-heading"><p className="eyebrow">CONFIGURACIÓN DE AIBID</p><h2>Vistas previas</h2><p>Configura las representaciones de Word y Excel y su espacio temporal.</p></header><Notice text={error}/><Notice text={success} kind="success"/>{settings&&<>
 <section className="card"><div className="section-heading"><h2>Caché de vistas previas</h2><button className="secondary" disabled={busy} onClick={()=>void load().catch(cause=>setError(message(cause)))}>Actualizar estado</button></div><p><strong>{(settings.used_bytes/1048576).toFixed(1)} MB</strong> utilizados · {settings.entries} vistas disponibles</p><p>La caché se guarda en el estado privado de AIBID. Al alcanzar el límite se eliminan las vistas utilizadas menos recientemente. Los originales, el texto indexado y los expedientes se conservan.</p>
 <form onSubmit={event=>{event.preventDefault();void save();}}>
 <label className="check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Habilitar vistas previas</label>
 <div className="filters"><label>Tamaño máximo de caché (MB)<input type="number" min={1} max={20480} required value={settings.maximum_cache_mb} onChange={e=>setSettings({...settings,maximum_cache_mb:Number(e.target.value)})}/></label><label>Antigüedad máxima sin uso (días)<input type="number" min={1} max={365} required value={settings.maximum_idle_days} onChange={e=>setSettings({...settings,maximum_idle_days:Number(e.target.value)})}/></label><label>Tamaño máximo del original (MB)<input type="number" min={1} max={512} required value={settings.maximum_source_mb} onChange={e=>setSettings({...settings,maximum_source_mb:Number(e.target.value)})}/></label></div>
 <label className="check"><input type="checkbox" checked={settings.automatic_cleanup} onChange={e=>setSettings({...settings,automatic_cleanup:e.target.checked})}/>Limpieza automática por antigüedad</label><p className="muted">La limpieza se comprueba al iniciar, cada hora y al publicar nuevas vistas. El límite de espacio se aplica siempre. Cada conversión tiene hasta dos minutos y su PDF puede ocupar hasta 64 MB.</p>
 <h3>Conversor de Word y Excel</h3><p role="status">{settings.converter_available?'LibreOffice detectado.':'LibreOffice no está disponible en el servidor.'}</p><p>Las vistas previas de Word y Excel requieren LibreOffice en el equipo donde corre AIBID. Su ausencia no impide extraer, buscar o descargar originales. Se detectan las ubicaciones habituales; si usas otra, indica su ejecutable. La conversión utiliza un perfil temporal con macros deshabilitadas.</p><p><a href="https://www.libreoffice.org/download/" target="_blank" rel="noreferrer">Descargar LibreOffice para Windows o macOS</a>. En Ubuntu 24.04: <code>sudo apt install libreoffice-writer libreoffice-calc</code>.</p><label>Ruta de LibreOffice (opcional)<input value={settings.converter_path} onChange={e=>setSettings({...settings,converter_path:e.target.value})} placeholder="Detección automática"/></label><p className="muted">Windows: soffice.com · macOS: LibreOffice.app/Contents/MacOS/soffice · Ubuntu: libreoffice. No incluyas argumentos.</p><button disabled={busy}>Guardar vistas previas</button>
 </form></section><section className="card"><h2>Limpieza manual</h2><p>Elimina solo las vistas guardadas y sus solicitudes pendientes. Los documentos, índices y auditoría permanecen intactos. Las conversiones activas no volverán a publicar la caché retirada.</p><label className="check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Confirmo que deseo vaciar la caché de vistas previas</label><button className="secondary" disabled={busy||!confirm} onClick={()=>void clear()}>Vaciar caché de vistas previas</button></section>
 </>}</>;
}
