import { useState } from 'react';
import type { Concurrency } from './ProcessingSettings';
import { api, formatDate, message, type Page } from './api';
import { Notice, usePolling } from './components';
import { diagnosticLabel, jobLabel, type Job, type Library } from './libraryTypes';

interface Scan { id: string; root_id: string; server_path: string; status: string; started_at: string; updated_at: string; completed_at: string; current_path: string; directories: number; pending_directories: number; files: number; unchanged: number; hashed: number; excluded: number; errors: number; paused: boolean }
interface Report { workers: Concurrency; performance: { native_active: number; ocr_active: number; waiting_ocr: number; queued: number; documents_per_minute: number; average_seconds: number; window_minutes: number }; stats: Record<string, number>; scans: Scan[]; active_jobs: Job[]; scan_errors: { root_id: string; relative_path: string; error_code: string; occurred_at: string }[] }
const taskNames: Record<string, string> = { scan: 'Reconciliar carpeta', extract: 'Extraer texto y OCR', verify_managed: 'Verificar integridad', materialize: 'Guardar documento definitivo' };
const operationNames: Record<string, string> = { scan: 'Descubriendo archivos', extract: 'Preparando extracción', snapshot: 'Leyendo y verificando PDF', native: 'Extrayendo texto', waiting_ocr: 'Esperando turno de OCR', render: 'Preparando imagen para OCR', publishing: 'Guardando texto e índice', ocr: 'Reconociendo texto con OCR', empty: 'Página sin texto', verify_managed: 'Verificando integridad', materialize: 'Guardando documento definitivo' };
function elapsed(start: string, end?: string) { if (!start) return '—'; const seconds = Math.max(0, Math.floor(((end ? new Date(end).getTime() : Date.now()) - new Date(start).getTime()) / 1000)); return `${Math.floor(seconds / 3600)} h ${Math.floor(seconds % 3600 / 60)} min ${seconds % 60} s`; }
function Progress({ job }: { job: Job }) {
  return <><strong>{operationNames[job.operation] || operationNames[job.job_type] || job.job_type}</strong>{job.total_units ? <><progress value={job.completed_units} max={job.total_units} aria-label="Avance por páginas" /><span>{Math.floor(job.completed_units * 100 / job.total_units)}% · {job.completed_units} de {job.total_units} páginas</span></> : <><progress aria-label="Procesando; total aún desconocido" /><span>En curso · {elapsed(job.started_at)}</span></>}</>;
}
export function LibraryJobs({ library }: { library: Library }) {
  const report = usePolling<Report>(`/libraries/${library.id}/processing`);
  const [cursor, setCursor] = useState(''); const [previous, setPrevious] = useState<string[]>([]);
  const jobs = usePolling<Page<Job>>(`/libraries/${library.id}/jobs?cursor=${encodeURIComponent(cursor)}`);
  const [error, setError] = useState('');
  async function act(path: string, body: object = {}) { try { await api(path, { method: 'POST', body }); setError(''); report.reload(); jobs.reload(); } catch (cause) { setError(message(cause)); } }
  const stats = report.data?.stats;
  return <><Notice text={error || report.error || jobs.error} />
    <section className="card"><div className="section-heading"><div><h2>Procesamiento de {library.name}</h2><p className="muted">Actualización automática. El descubrimiento y la extracción avanzan de forma independiente.</p></div></div>
      {stats && <div className="metrics">{Object.entries({ total: 'Archivos registrados', linked: 'Vinculados', managed: 'Administrados', pending: 'Pendientes de contenido', processed: 'Procesados', errors: 'Con error de extracción', native: 'Solo texto directo', ocr: 'Con OCR' }).map(([key, label]) => <div className="metric" key={key}><strong>{stats[key]}</strong><span>{label}</span></div>)}</div>}
      <p className="muted">Cada archivo físico cuenta una vez, aunque tenga varias rutas. Las copias independientes cuentan por separado. Pendientes incluye en cola, en curso, pausados y cancelados sin contenido vigente.</p>
    </section>
    {report.data && <section className="card"><h2>Actividad de contenido</h2><div className="metrics">{Object.entries({native_active:'Extracción activa',ocr_active:'OCR activo',waiting_ocr:'Preparados para OCR',queued:'Documentos en cola'}).map(([key,label])=><div className="metric" key={key}><strong>{report.data!.performance[key as 'native_active']}</strong><span>{label}</span></div>)}</div><p>Límites compartidos entre bibliotecas: {report.data.workers.native_workers} extracción · {report.data.workers.ocr_workers} OCR · {report.data.workers.total_workers} simultáneos.</p><p>{report.data.performance.documents_per_minute.toFixed(1)} documentos/min · {report.data.performance.average_seconds.toFixed(1)} s por documento terminado. Ventana de {report.data.performance.window_minutes} minutos.</p><small>El promedio incluye lectura, espera de OCR y publicación. La velocidad por minuto usa la ventana completa, incluso si hubo inactividad.</small></section>}
    <section className="card"><h2>Reconciliación de carpetas</h2>{!report.data?.scans.length && <p>Sin recorridos registrados.</p>}{report.data?.scans.map(scan => <article className="scan-card" key={scan.id}>
      <strong className="path-text">{scan.server_path}</strong><p>{scan.paused ? 'Reconciliación pausada por el usuario' : scan.status === 'running' ? 'Descubriendo archivos · total aún desconocido' : scan.errors ? 'Recorrido incompleto: revisa las rutas con error' : scan.status === 'complete' ? 'Recorrido terminado' : 'Recorrido interrumpido'}</p>
      {scan.status === 'running' && !scan.paused && <progress aria-label="Descubrimiento en curso" />}
      <p className="path-text">Ruta actual o última: {scan.current_path || '—'}</p><p>{scan.files} rutas PDF registradas · {scan.unchanged} sin cambios · {scan.hashed} verificados por contenido · {scan.errors} rutas con error</p>
      <p>{scan.directories} carpetas recorridas · {scan.pending_directories} pendientes conocidas · {scan.excluded} carpetas del sistema omitidas</p>
      {report.data?.active_jobs.filter(job=>job.job_type==='scan' && job.root_id===scan.root_id).map(job=><button key={job.id} className="secondary" disabled={job.cancelling} onClick={()=>void act(`/jobs/${job.id}/cancel`)}>{job.cancelling?'Cancelando…':'Cancelar recorrido'}</button>)}<small>Transcurrido: {elapsed(scan.started_at, scan.completed_at || (scan.paused ? scan.updated_at : undefined))} · Último avance: {formatDate(scan.updated_at)}</small>
      {scan.paused && <button className="secondary" onClick={() => void act(`/libraries/${library.id}/verify`, { root_id: scan.root_id })}>Reanudar reconciliación</button>}
      {scan.errors > 0 && library.permissions.includes('indexing.retry') && <button className="secondary" onClick={() => void act(`/roots/${scan.root_id}/retry-errors`)}>Reintentar rutas con error</button>}
    </article>)}</section>
    <section className="card"><h2>Trabajos activos</h2>{!report.data?.active_jobs.filter(job=>job.job_type!=='scan').length && <p>No hay trabajos ejecutándose en este momento.</p>}<div className="active-jobs">{report.data?.active_jobs.filter(job=>job.job_type!=='scan').map(job => <article className="scan-card" key={job.id}><h3>{job.filename || 'Recorrido de carpeta'}</h3><p className="path-text">{job.root_path} {job.relative_path && ` / ${job.relative_path}`}</p><Progress job={job} />{['scan', 'extract'].includes(job.job_type) && <button className="secondary" disabled={job.cancelling} onClick={() => void act(`/jobs/${job.id}/cancel`)}>{job.cancelling ? 'Cancelando…' : 'Cancelar trabajo'}</button>}</article>)}</div></section>
    {!!report.data?.scan_errors.length && <section className="card"><h2>Rutas que requieren atención</h2><p className="muted">Hasta 100 errores recientes. Las demás carpetas continúan procesándose.</p><div className="table-wrap"><table><thead><tr><th>Ruta relativa</th><th>Diagnóstico</th><th>Fecha</th></tr></thead><tbody>{report.data.scan_errors.map(issue => <tr key={issue.root_id + issue.relative_path}><td className="path-text">{issue.relative_path}</td><td>{diagnosticLabel[issue.error_code] || issue.error_code}</td><td>{formatDate(issue.occurred_at)}</td></tr>)}</tbody></table></div></section>}
    <section className="card job-history"><h2>Cola e historial de tareas</h2><div className="table-wrap"><table><thead><tr><th>Archivo o carpeta</th><th>Tarea</th><th>Estado</th><th>Intentos</th><th>Diagnóstico</th><th>Acciones</th></tr></thead><tbody>{jobs.data?.items.map(job => <tr key={job.id}><td><strong>{job.filename || job.root_path || library.name}</strong><small className="path-text">{job.relative_path}</small><small>{formatDate(job.created_at)} · {elapsed(job.started_at, job.finished_at)}</small></td><td>{taskNames[job.job_type]}</td><td>{jobLabel[job.status]}</td><td>{job.attempt_count} / 5</td><td>{diagnosticLabel[job.last_error_code] || job.last_error_code || '—'}</td><td>{['failed', 'cancelled'].includes(job.status) && library.permissions.includes('indexing.retry') && <button className="text-button" onClick={() => void act(`/jobs/${job.id}/retry`, { reason: 'Reintento solicitado desde Procesamiento' })}>Reintentar</button>}{['queued', 'retry_wait', 'paused'].includes(job.status) && ['scan', 'extract'].includes(job.job_type) && <button className="text-button" onClick={() => void act(`/jobs/${job.id}/cancel`)}>Cancelar</button>}</td></tr>)}</tbody></table></div>
      {jobs.data?.items.length === 0 && <p>No hay tareas registradas.</p>}
      <div className="actions"><button className="secondary" disabled={!previous.length} onClick={() => { setCursor(previous[previous.length - 1]); setPrevious(previous.slice(0, -1)); }}>Anterior</button><span>Página {previous.length + 1}</span><button className="secondary" disabled={!jobs.data?.next_cursor} onClick={() => { setPrevious([...previous, cursor]); setCursor(jobs.data?.next_cursor || ''); }}>Siguiente</button></div>
    </section>
  </>;
}
