import { useEffect, useState } from 'react';
import { api, message } from './api';
import { Notice } from './components';
export interface Concurrency { mode: string; native_workers: number; ocr_workers: number; total_workers: number }
interface Settings { configuration: Concurrency; effective: Concurrency; revision: number; resources: {logical_cpus: number; physical_cores: number; available_cpus: number; memory_bytes: number; available_memory_bytes: number; notes: string[]} }
export function ProcessingSettings() {
 const [settings,setSettings]=useState<Settings|null>(null);const [configuration,setConfiguration]=useState<Concurrency>({mode:'auto',native_workers:2,ocr_workers:1,total_workers:2});const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();api<Settings>('/system/processing',{signal:abort.signal}).then(value=>{setSettings(value);setConfiguration({...value.effective,mode:value.configuration.mode});}).catch(cause=>{if(!abort.signal.aborted)setError(message(cause));});return()=>abort.abort();},[]);
 const gb=(n:number)=>n?`${(n/2**30).toFixed(1)} GB`:'No disponible';
 return <><header className="page-heading"><p className="eyebrow">CONFIGURACIÓN DE AIBID</p><h1>Procesamiento del equipo</h1><p>Comparte los recursos entre las bibliotecas y las demás aplicaciones del equipo.</p></header><Notice text={error}/><Notice text={success} kind="success"/>
 {settings&&<><section className="card"><h2>Recursos detectados al iniciar</h2><div className="metrics"><div className="metric"><strong>{settings.resources.physical_cores||'—'}</strong><span>Núcleos físicos</span></div><div className="metric"><strong>{settings.resources.logical_cpus}</strong><span>Procesadores lógicos</span></div><div className="metric"><strong>{settings.resources.available_cpus}</strong><span>CPU disponibles para AIBID</span></div><div className="metric"><strong>{gb(settings.resources.available_memory_bytes)}</strong><span>Memoria disponible de {gb(settings.resources.memory_bytes)}</span></div></div>{settings.resources.notes.map(note=><p className="muted" key={note}>{note}</p>)}</section>
 <section className="card"><h2>Concurrencia</h2><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setSuccess('');try{const result=await api<Settings>('/system/processing',{method:'PUT',body:{configuration,revision:settings.revision}});setSettings(result);setConfiguration({...result.effective,mode:result.configuration.mode});setSuccess('Configuración guardada. Se aplicará a nuevos trabajos en unos segundos; los trabajos activos terminan normalmente.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}}>
 <label>Modo de procesamiento<select value={configuration.mode} onChange={event=>setConfiguration({...configuration,mode:event.target.value})}><option value="auto">Automático (recomendado)</option><option value="manual">Manual</option></select></label><p>El modo automático reserva capacidad para otras aplicaciones. El límite general incluye extracción y OCR; la reconciliación usa un worker adicional.</p>
 {configuration.mode==='manual'&&<div className="filters">{([['native_workers','Máximo de extracción directa',8],['ocr_workers','Máximo de OCR',4],['total_workers','Límite general de contenido',8]] as const).map(([key,label,max])=><label key={key}>{label}<input type="number" min={1} max={max} required value={configuration[key]} onChange={event=>setConfiguration({...configuration,[key]:Number(event.target.value)})}/></label>)}</div>}
 <p>Configuración vigente: hasta {settings.effective.native_workers} de extracción · {settings.effective.ocr_workers} de OCR · {settings.effective.total_workers} operaciones de contenido simultáneas.</p><p className="muted">Este límite controla cuántas operaciones se ejecutan a la vez; no fija un porcentaje de CPU. Los cambios se conservan al reiniciar.</p><button disabled={busy}>{busy?'Guardando…':'Guardar procesamiento'}</button></form></section></>}
 </>;
}
