import { ProcessingPolicy } from './ProcessingPolicy';
import { useEffect, useState } from 'react';
import { api, message } from './api';
import { Notice } from './components';
export interface Concurrency { mode: string; native_workers: number; ocr_workers: number; total_workers: number }
interface Settings { configuration: Concurrency; effective: Concurrency; revision: number; resources: {logical_cpus: number; physical_cores: number; available_cpus: number; memory_bytes: number; available_memory_bytes: number; notes: string[]} }
export function ProcessingSettings() {
 const [settings,setSettings]=useState<Settings|null>(null);const [configuration,setConfiguration]=useState<Concurrency>({mode:'auto',native_workers:2,ocr_workers:1,total_workers:2});const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();api<Settings>('/system/processing',{signal:abort.signal}).then(value=>{setSettings(value);setConfiguration({...value.effective,mode:value.configuration.mode});}).catch(cause=>{if(!abort.signal.aborted)setError(message(cause));});return()=>abort.abort();},[]);
 const gb=(n:number)=>n?`${(n/2**30).toFixed(1)} GB`:'No disponible';
 return <><header className="page-heading"><p className="eyebrow">CONFIGURACIÓN DE AIBID</p><h1>Procesamiento del equipo</h1><p>Comparte los recursos entre las bibliotecas y las demás aplicaciones del equipo.</p></header><Notice text={error}/><Notice text={success} kind="success"/>
 <ProcessingPolicy/>
 {settings&&<><section className="card"><h2>Recursos detectados al iniciar</h2><div className="metrics"><div className="metric"><strong>{settings.resources.physical_cores||'—'}</strong><span>Núcleos físicos</span></div><div className="metric"><strong>{settings.resources.logical_cpus}</strong><span>Procesadores lógicos</span></div><div className="metric"><strong>{settings.resources.available_cpus}</strong><span>CPU disponibles para AIBID</span></div><div className="metric"><strong>{gb(settings.resources.available_memory_bytes)}</strong><span>Memoria disponible de {gb(settings.resources.memory_bytes)}</span></div></div>{settings.resources.notes.map(note=><p className="muted" key={note}>{note}</p>)}</section>
 <section className="card"><h2>Procesos simultáneos</h2><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setSuccess('');try{const result=await api<Settings>('/system/processing',{method:'PUT',body:{configuration,revision:settings.revision}});setSettings(result);setConfiguration({...result.effective,mode:result.configuration.mode});setSuccess('Configuración guardada. Se aplicará a nuevos trabajos en unos segundos; los trabajos activos terminan normalmente.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}}>
 <label>Modo de procesamiento<select value={configuration.mode} onChange={event=>setConfiguration({...configuration,mode:event.target.value})}><option value="auto">Automático (recomendado)</option><option value="manual">Manual</option></select></label><p>El modo automático reserva capacidad para otras aplicaciones. La revisión de carpetas avanza por separado.</p>
 {configuration.mode==='manual'&&<><p id="processing-count-help">Cada proceso atiende un documento a la vez. Los procesos comparten los {settings.resources.available_cpus} procesadores lógicos disponibles para AIBID. El máximo configurable de 8 procesos es un límite de la aplicación; más procesos pueden competir por CPU y memoria sin aumentar la velocidad.</p><div className="filters">{([['native_workers','Máximo de extracción directa',8],['ocr_workers','Máximo de OCR',4],['total_workers','Límite general de contenido',8]] as const).map(([key,label,max])=><label key={key}>{label}<span className="input-unit"><input aria-label={`${label} (procesos)`} aria-describedby="processing-count-help processing-total-help" type="number" min={key==='total_workers'?Math.max(1,configuration.native_workers,configuration.ocr_workers):1} max={max} required value={configuration[key]} onChange={event=>setConfiguration({...configuration,[key]:Number(event.target.value)})}/><span aria-hidden="true">procesos</span></span></label>)}</div><p id="processing-total-help" className="muted">El límite general se comparte entre extracción y OCR y debe ser igual o mayor que cada límite individual. Por ejemplo, 4 de extracción, 2 de OCR y un límite general de 4 permiten hasta 4 procesos en total.</p></>}
 <p>Configuración guardada: hasta {settings.effective.native_workers} procesos de extracción · {settings.effective.ocr_workers} procesos de OCR · {settings.effective.total_workers} procesos simultáneos en total.</p><p className="muted">Estos valores cuentan procesos, no núcleos ni porcentajes de CPU. Los cambios se aplican al guardar y se conservan al reiniciar.</p><button disabled={busy}>{busy?'Guardando…':'Guardar procesamiento'}</button></form></section></>}
 </>;
}
