import { useEffect, useState } from 'react';
import { api, formatDate, message } from './api';
import { Notice } from './components';
import { Accordion } from './Accordion';
import { CursorControls, useCursorPage } from './CursorPage';

export interface DiagnosticEvent {id:string;occurred_at:string;last_occurred_at:string;module:string;code:string;severity:string;status:string;message:string;context:Record<string,string|number>;occurrences:number;revision:number}
export const moduleLabels:Record<string,string>={processing:'Procesamiento',scan:'Lectura de carpetas',preview:'Vistas previas',watcher:'Vigilancia',http:'Servidor web',system:'Sistema',licensing:'Licenciamiento'};
export const severityLabels:Record<string,string>={info:'Información',warning:'Advertencia',error:'Error',critical:'Crítico'};
interface Policy {retention_days:number;maximum_events:number;revision:number}
export function SystemErrors(){
 const [filters,setFilters]=useState({from:'',to:'',module:'',severity:'',status:''});
 const [query,setQuery]=useState('');const [error,setError]=useState(''),[notice,setNotice]=useState('');
 const [policy,setPolicy]=useState<Policy|null>(null),[busy,setBusy]=useState(false),[diagnostic,setDiagnostic]=useState('');
 const events=useCursorPage<DiagnosticEvent>(`/system/errors?${query}`);
 useEffect(()=>{const controller=new AbortController();api<Policy>('/system/error-policy',{signal:controller.signal}).then(setPolicy).catch(cause=>{if(!controller.signal.aborted)setError(message(cause))});return()=>controller.abort()},[]);
 async function review(event:DiagnosticEvent){setBusy(true);setError('');try{await api(`/system/errors/${event.id}`,{method:'PATCH',body:{status:event.status==='open'?'reviewed':'open',revision:event.revision}});events.reload()}catch(cause){setError(message(cause));events.reload()}finally{setBusy(false)}}
 async function copy(event:DiagnosticEvent){setBusy(true);setNotice('');setError('');try{const value=await api<object>(`/system/errors/${event.id}/diagnostic`);const text=JSON.stringify(value,null,2);setDiagnostic(text);try{await navigator.clipboard.writeText(text);setNotice('Información de diagnóstico copiada.')}catch{setNotice('El navegador no permite copiar automáticamente. Selecciona el diagnóstico de abajo y cópialo.')}}catch(cause){setError(message(cause))}finally{setBusy(false)}}
 return <><header className="page-heading"><p className="eyebrow">SISTEMA</p><h1>Errores y diagnósticos</h1><p>Incidencias internas para revisión y soporte. Las acciones de los usuarios siguen en Auditoría.</p><p className="muted">Este registro recoge incidencias a partir de esta versión; no reconstruye errores anteriores a la actualización.</p></header><Notice text={error||events.error}/><Notice text={notice} kind="success"/>
 <section className="card"><div className="section-heading"><h2>Registros del sistema</h2><button className="secondary" onClick={events.reload} disabled={events.busy}>Actualizar registros</button></div>
 <form className="filters" onSubmit={event=>{event.preventDefault();setError('');if(filters.from&&filters.to&&filters.from>filters.to){setError('La fecha inicial debe ser anterior o igual a la final.');return}const q=new URLSearchParams();for(const key of ['module','severity','status'] as const){if(filters[key])q.set(key,filters[key])}if(filters.from)q.set('from',new Date(`${filters.from}T00:00:00`).toISOString());if(filters.to){const date=new Date(`${filters.to}T00:00:00`);date.setDate(date.getDate()+1);q.set('to',date.toISOString())}setQuery(q.toString());events.reload()}}>
 <label>Desde<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Hasta<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label>
 <label>Módulo<select value={filters.module} onChange={e=>setFilters({...filters,module:e.target.value})}><option value="">Todos los módulos</option>{Object.entries(moduleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label>Severidad<select value={filters.severity} onChange={e=>setFilters({...filters,severity:e.target.value})}><option value="">Todos los niveles</option>{Object.entries(severityLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label>Estado del diagnóstico<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos los estados</option><option value="open">Pendiente de revisión</option><option value="reviewed">Revisado</option></select></label><button>Aplicar filtros</button></form>
 <p className="muted">Las fechas filtran la última aparición, según la zona horaria de tu navegador. Marcar revisado no repara ni reintenta el trabajo; una nueva aparición vuelve a dejarlo pendiente.</p>
 <div className="table-wrap"><table className="system-errors-table" aria-label="Errores del sistema"><thead><tr><th>Última aparición</th><th>Módulo</th><th>Severidad</th><th>Diagnóstico</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{events.items.map(event=><tr key={event.id}><td>{formatDate(event.last_occurred_at)}<small>{event.occurrences} {event.occurrences===1?'aparición':'apariciones'}</small></td><td>{moduleLabels[event.module]}</td><td><span className={`badge ${event.severity==='critical'?'diagnostic-critical':''}`}>{severityLabels[event.severity]}</span></td><td><strong>{event.code}</strong><p>{event.message}</p><Accordion title="Contexto del diagnóstico"><p>Primera aparición: {formatDate(event.occurred_at)}</p><p className="path-text">Referencia: {event.id}</p><pre className="diagnostic-context">{JSON.stringify(event.context,null,2)}</pre></Accordion></td><td>{event.status==='open'?'Pendiente de revisión':'Revisado'}</td><td><div className="actions"><button className="secondary compact" disabled={busy} onClick={()=>void copy(event)}>Copiar información de diagnóstico</button><button className="text-button" disabled={busy} onClick={()=>void review(event)}>{event.status==='open'?'Marcar revisado':'Marcar pendiente'}</button></div></td></tr>)}</tbody></table></div>
 {events.busy&&<p role="status">Consultando diagnósticos…</p>}{!events.busy&&!events.error&&!events.items.length&&<p className="empty-state">No hay diagnósticos para estos filtros.</p>}<CursorControls page={events} label="Diagnósticos"/>
 </section>
 {diagnostic&&<section className="card"><h2>Información para soporte</h2><label>Diagnóstico para copiar<textarea className="support-diagnostic" readOnly rows={12} value={diagnostic} onFocus={event=>event.target.select()}/></label><p className="muted">Incluye versión, sistema operativo, código e identificadores técnicos. No incluye nombres de archivos, rutas, contenido documental ni credenciales.</p><button className="secondary" onClick={()=>setDiagnostic('')}>Cerrar diagnóstico</button></section>}
 <section className="card"><Accordion title="Retención de diagnósticos">{policy&&<form className="form-grid" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{setPolicy(await api<Policy>('/system/error-policy',{method:'PUT',body:policy}));setNotice('Retención guardada. Se eliminaron los diagnósticos que superaban estos límites.');events.reload()}catch(cause){setError(message(cause));setPolicy(await api<Policy>('/system/error-policy').catch(()=>policy))}finally{setBusy(false)}}}>
 <label>Días de conservación<input type="number" min={1} max={365} required value={policy.retention_days} onChange={event=>setPolicy({...policy,retention_days:Number(event.target.value)})}/></label><label>Máximo de registros<input type="number" min={100} max={50000} required value={policy.maximum_events} onChange={event=>setPolicy({...policy,maximum_events:Number(event.target.value)})}/></label><p>Se conservan hasta {policy.maximum_events} registros de los últimos {policy.retention_days} días. Las repeticiones del mismo problema se agrupan. Guardar aplica inmediatamente estos límites, también a registros pendientes. La Auditoría se conserva.</p><button disabled={busy}>Guardar retención</button></form>}</Accordion></section></>;
}
